const routes = [
    {
        id: 1,
        name: "苍岩山",
        location: "井陉县",
        difficulty: "medium",
        difficultyLabel: "中等",
        duration: "full",
        durationLabel: "一日",
        distance: "8 km",
        elevation: "约 600 m",
        bestSeason: "春秋两季",
        seasonTags: ["spring", "autumn"],
        theme: { sky: ["#a8d5c1", "#6a9c89"], far: "#5a8c7a", mid: "#3d6e5a", near: "#1f4a3a", accent: "temple", sun: "warm", primary: "#3d6e5a", soft: "#e0ebe3" },
        ratings: { stamina: 3, technical: 2, exposure: 2, retreat: 5, signal: 4 },
        techGrade: "T2",
        epithet: "苍岩怀古",
        poem: {
            title: "终南别业(节)",
            author: "王维",
            dynasty: "唐",
            lines: ["中岁颇好道", "晚家南山陲", "行到水穷处", "坐看云起时"],
            note: "登苍岩,见桥楼殿凌空,正合王摩诘'坐看云起'之境。"
        },
        description: "国家5A级景区,以悬空寺、桥楼殿著称,自然景观与古建筑融为一体,适合家庭出游。",
        features: [
            "中国三大悬空寺之一,桥楼殿建在两山之间的天然石桥上",
            "《卧虎藏龙》《赤壁》取景地,电影感拉满",
            "佛、道、儒三教合一的古建筑群,文化厚度足",
            "山路虽长但台阶完备,腿脚一般也能完成"
        ],
        waypoints: [
            { time: "08:30", name: "景区南门", elev: "300m", scene: "🏞️", vista: "古朴牌坊门洞,两侧苍翠松柏夹道,清晨入园人少", note: "建议早到,避开旅游团" },
            { time: "09:15", name: "桥楼殿", elev: "560m", scene: "🏯", vista: "凌空横跨两崖的悬空殿,《卧虎藏龙》经典机位", note: "经典取景点,正面拍照最佳" },
            { time: "10:00", name: "福庆寺主殿", elev: "620m", scene: "⛩️", vista: "千年古刹红墙黛瓦,殿前古碑林立檀香袅袅", note: "可在此祈福,殿内有古碑" },
            { time: "11:30", name: "公主峰观景台", elev: "830m", scene: "🏔️", vista: "峡谷俯瞰全景,层峦叠嶂直至天际", note: "俯瞰整个景区峡谷" },
            { time: "13:00", name: "蝴蝶谷", elev: "650m", scene: "🦋", vista: "溪水潺潺花木扶疏,夏日蝴蝶成群飞舞", note: "自带午餐,溪边休息" },
            { time: "15:30", name: "返回南门", elev: "300m", scene: "🌲", vista: "下山林荫小道,夕阳穿林而过", note: "可走另一侧步道下山看不同景色" }
        ],
        hiddenSpots: [
            "桥楼殿下方有一处少人知的拍摄机位,需绕到对岸石阶,能拍到悬空寺与峡谷全景",
            "藏经楼后山小路通往一处明代碑刻,导游一般不带,但管理处询问可指路",
            "景区外2公里的于家石头村是石头建筑奇观,联游性价比超高"
        ],
        photography: "上午10点前桥楼殿正面有光、下午3点后福庆寺方向逆光剪影,适合人像。",
        food: "山下井陉抿须面、缸炉烧饼、井陉煎饼,推荐'天长古镇'内的老店。",
        cuisine: {
            tagline: "山下天长古镇,千年驿站的烟火",
            signature: { name: "井陉抿须面", icon: "🍜", price: "¥15-25", desc: "手搓荞麦面,过水冷拌或浇老汤,劲道带豆香,是车马劳顿后第一碗热乎" },
            snack:     { name: "缸炉烧饼", icon: "🥯", price: "¥3-5/个", desc: "黄泥缸壁烤就,外脆芝麻香,中夹咸甜两味,徒步包里塞两个续命" },
            drink:     { name: "井陉煎饼配豆腐脑", icon: "🥣", price: "¥10",   desc: "薄脆煎饼裹刚出锅嫩豆腐脑,胡椒油一淋,寒气尽散" },
            shop:      "推荐:天长古镇·王家老烧饼铺 / 西关刘家面馆(下山驾车 15 分钟)",
            seasonal:  { summer: "夏宜:荞麦凉面 + 自酿酸梅汤", winter: "冬宜:羊汤抿须 + 烫一壶老白干" },
            tea:       "宜配:本地连翘茶,微涩回甘,清燥解乏",
            verse:     "「日暮苍山远,寒舍犬吠归人」 — 一碗热面胜十里春风"
        },
        route: "景区南门入口 → 桥楼殿 → 福庆寺 → 公主峰 → 蝴蝶谷 → 原路返回",
        access: "石家庄市区出发,沿G5京昆高速→苍岩山出口,车程约2小时。",
        tips: "夏季注意防晒,景区台阶较多,建议穿登山鞋。门票约65元。",
        gear: ["登山鞋(防滑)", "1.5L 饮水", "防晒霜+遮阳帽", "薄外套", "干粮/能量棒", "现金/手机支付"],
        emergency: { local: "井陉文旅局 0311-82021290", rescue: "井陉景区救援 0311-82033555", general: "110 / 120" },
        gpxNote: "景区线路完备,无需GPX。如需可下载景区官方电子地图。",
        soundscape: { name: "古寺钟声", search: "temple bell mountain wind" },
        coords: { lon: 114.06, lat: 37.93 },
        lastUpdated: "2026-05-10"
    },
    {
        id: 2,
        name: "驼梁山",
        location: "平山县",
        difficulty: "hard",
        difficultyLabel: "困难",
        duration: "multi",
        durationLabel: "多日",
        distance: "15 km",
        elevation: "约 1200 m",
        bestSeason: "夏季避暑首选",
        seasonTags: ["summer"],
        theme: { sky: ["#c4dce8", "#7eb09b"], far: "#a8c4b8", mid: "#5a8c7a", near: "#2d5a3d", accent: "snow", sun: "cool", primary: "#5a8c7a", soft: "#dee9e5" },
        ratings: { stamina: 5, technical: 3, exposure: 3, retreat: 2, signal: 2 },
        techGrade: "T3",
        epithet: "驼梁望云",
        poem: {
            title: "望庐山瀑布",
            author: "李白",
            dynasty: "唐",
            lines: ["日照香炉生紫烟", "遥看瀑布挂前川", "飞流直下三千尺", "疑是银河落九天"],
            note: "驼梁瀑布群飞泻千仞,合谪仙人'银河九天'之气魄。"
        },
        description: "海拔2281米,为河北五大高峰之一,夏季平均气温19℃,有“三省一市最高峰”之称。",
        features: [
            "海拔2281m,晋冀两省界峰,登顶可一脚踏两省",
            "夏季气温19℃,堪比东北凉爽,被誉为'天然空调'",
            "森林覆盖率98%,空气负氧离子浓度极高",
            "云海+日出+银河三重奏,摄影圣地",
            "唯一一条可在山顶露营的路线,推荐徒步爱好者"
        ],
        waypoints: [
            { time: "Day1 09:00", name: "南台入口", elev: "1100m", scene: "🚪", vista: "高山入口牌坊,远山笼罩云雾", note: "购票、登记入山" },
            { time: "Day1 11:00", name: "飞来石", elev: "1500m", scene: "🪨", vista: "悬于崖边的天然奇石,孤峰耸立", note: "天然奇石,绝佳休息点" },
            { time: "Day1 14:00", name: "通天梁", elev: "1900m", scene: "🥾", vista: "陡峭石阶通天而上,两侧密林深锁", note: "陡坡路段,小心湿滑" },
            { time: "Day1 16:30", name: "云顶营地", elev: "2200m", scene: "⛺", vista: "草甸营地晚霞绚烂,帐篷点点", note: "扎营,看日落与星空" },
            { time: "Day2 04:30", name: "主峰看日出", elev: "2281m", scene: "🌅", vista: "云海翻涌+日出金光万丈,界峰标志石", note: "云海日出绝景" },
            { time: "Day2 07:00", name: "返回拔营", elev: "2200m", scene: "🎒", vista: "晨雾营地,远山仍藏云中", note: "整理装备" },
            { time: "Day2 12:00", name: "北坡下山", elev: "1300m", scene: "🌲", vista: "原始森林步道,松涛阵阵", note: "另一条线下撤看不同风景" }
        ],
        hiddenSpots: [
            "云顶营地东侧500米有一处无名草甸,基本无人涉足,夜观银河无光污染",
            "下山途中'瀑布群岔路'可绕至冰瀑(冬季)和野生猴群活动区",
            "山下'山炸店村'有藏族风格小院民宿,可寄存装备并提供热水洗浴"
        ],
        photography: "主峰云海最佳时机为日出后30分钟,雨后第二天云海概率90%。星空建议农历月初。",
        food: "山下平山农家菜:压饸饹、缸炉烧饼、平山黑猪肉炖小笨鸡。",
        cuisine: {
            tagline: "高山归来,平山农家土灶等你",
            signature: { name: "平山黑猪肉炖笨鸡", icon: "🍲", price: "¥80-120/份", desc: "土灶柴火慢炖三小时,黑猪带皮配跑山鸡,汤色金黄油润不腻,登顶之后第一锅热汤" },
            snack:     { name: "压饸饹", icon: "🍝", price: "¥18-25", desc: "莜麦面压制,浇骨头汤+辣椒油+腌韭花,登山后补碳水的山民秘籍" },
            drink:     { name: "山炸店小米粥", icon: "🍚", price: "¥5",  desc: "平山小米熬到米油泛黄,配一碟自家咸菜,胃壁瞬间被温柔包裹" },
            shop:      "推荐:山炸店村·老李家土灶(露营驴友补给地) / 驼梁山下·农家小院",
            seasonal:  { summer: "夏宜:凉调豆角丝 + 冰镇绿豆汤", winter: "冬宜:全套土灶锅 + 自酿地瓜烧" },
            tea:       "宜配:平山金莲花茶,高山所产,清热降火",
            verse:     "「莫笑农家腊酒浑,丰年留客足鸡豚」 — 陆游写此处,亦不为过"
        },
        route: "南台入口 → 飞来石 → 通天梁 → 主峰云顶 → 北坡下山 / 露营",
        access: "石家庄→平山→驼梁景区,车程约3.5小时,建议自驾。",
        tips: "高海拔地区昼夜温差大,即使夏季也需带保暖衣物。建议两日行程,可在景区或山下民宿住宿。",
        gear: ["登山鞋(高帮)", "登山杖", "3L 饮水", "防风冲锋衣", "保暖抓绒/羽绒", "帐篷+睡袋(露营)", "头灯", "急救包", "保险/身份证", "卫星通讯(强烈推荐)"],
        emergency: { local: "平山文旅局 0311-82911234", rescue: "驼梁景区救援 0311-82939999", general: "110 / 120 / 蓝天救援 0311-87085222" },
        gpxNote: "强烈建议下载 GPX 离线轨迹文件,山顶部分区域无信号。",
        soundscape: { name: "风过松林", search: "wind pine forest mountain" },
        coords: { lon: 113.59, lat: 38.74 },
        lastUpdated: "2026-05-15"
    },
    {
        id: 3,
        name: "抱犊寨",
        location: "鹿泉区",
        difficulty: "easy",
        difficultyLabel: "轻松",
        duration: "half",
        durationLabel: "半日",
        distance: "4 km",
        elevation: "约 300 m",
        bestSeason: "全年适宜",
        seasonTags: ["spring", "summer", "autumn", "winter"],
        theme: { sky: ["#d4e8d8", "#8bb89e"], far: "#7ea88e", mid: "#5a8c70", near: "#3a6e50", accent: "flat", sun: "warm", primary: "#5a8c70", soft: "#e3ede5" },
        ratings: { stamina: 1, technical: 1, exposure: 1, retreat: 5, signal: 5 },
        techGrade: "T1",
        epithet: "抱犊望平",
        poem: {
            title: "登抱犊寨",
            author: "苏轼(化用)",
            dynasty: "宋",
            lines: ["不识庐山真面目", "只缘身在此山中", "山顶平如台", "万里入襟胸"],
            note: "抱犊山顶平阔,登顶方知华北平原之辽阔。"
        },
        description: "距石家庄市区仅16公里,有“天下奇寨”美誉,山顶平坦广阔,可俯瞰华北平原。",
        features: [
            "市区16km,'最近的山',下午出发也来得及",
            "山顶平坦如运动场,占地600余亩,有'山顶平原'之奇",
            "韩信背水之战古战场遗址,历史厚重",
            "南北朝时期金阙宫为道教圣地,香火延续至今",
            "可缆车上下,亲子/老人完全无负担"
        ],
        waypoints: [
            { time: "13:30", name: "山下停车场", elev: "150m", scene: "🅿️", vista: "山下广场仰视'寨'字山顶,缆车索道斜跨", note: "停车免费,设施齐备" },
            { time: "13:50", name: "缆车站", elev: "180m", scene: "🚡", vista: "彩色缆车缓缓上升,俯瞰山下村庄绿野", note: "缆车7分钟直达山顶" },
            { time: "14:10", name: "南天门", elev: "450m", scene: "🏛️", vista: "明代古城墙巍然耸立,'南天门'三字苍劲", note: "山顶入口,有古城墙" },
            { time: "14:40", name: "韩信祠", elev: "460m", scene: "⛩️", vista: "祠内壁画讲述背水一战,古朴庄重", note: "祠内有韩信生平壁画" },
            { time: "15:30", name: "金阙宫", elev: "455m", scene: "🛕", vista: "金顶道观在阳光下熠熠生辉,香烟缭绕", note: "石家庄最大道观,可上香" },
            { time: "16:30", name: "环山步道", elev: "440m", scene: "🌅", vista: "山顶平原步道,夕阳将云霞染红", note: "绕山顶一圈看夕阳" },
            { time: "17:30", name: "下山", elev: "150m", scene: "🚡", vista: "缆车下山华北平原一览无余", note: "可走步道或缆车" }
        ],
        hiddenSpots: [
            "西侧'天井'是天然下凹平台,游客极少,可坐看华北平原日落",
            "万亩柏林深处有'求子洞'石窟,需问当地人才能找到",
            "山下东沟村有正宗的'抱犊寨石锅鸡',是本地人才知道的下山饭"
        ],
        photography: "傍晚17点后金阙宫琉璃瓦在夕阳下金光闪闪,人少景美。",
        food: "鹿泉肉饼、抱犊寨石锅鸡、华北油面茶。",
        cuisine: {
            tagline: "市区最近的山,有市区最方便的味",
            signature: { name: "抱犊寨石锅鸡", icon: "🍳", price: "¥98-158", desc: "麦饭石锅高温焗鸡,鸡皮焦脆肉嫩出油,鸡油里炖香菇豆腐,是本地人才知道的下山仪式" },
            snack:     { name: "鹿泉肉饼", icon: "🥟", price: "¥10-15/个", desc: "面皮薄如蝉翼,牛肉葱油填满每个褶,咬下去汁水四溢,刚出锅烫嘴最香" },
            drink:     { name: "油面茶", icon: "☕", price: "¥6",   desc: "炒小麦粉调糊,撒芝麻花生,华北早点之王,徒步前后皆宜" },
            shop:      "推荐:东沟村·老石锅 / 鹿泉北街·二刘肉饼(车程 10-15 分钟)",
            seasonal:  { spring: "春宜:嫩荠菜煎饼 + 香椿摊蛋", autumn: "秋宜:山下柿饼 + 新榨核桃油凉面" },
            tea:       "宜配:本地金银花茶 / 华北米酒(就石锅鸡尤佳)",
            verse:     "「半亩方塘一鉴开,天光云影共徘徊」 — 山顶饱览天地,山下饱览一锅"
        },
        route: "停车场 → 步道上山(或缆车) → 南天门 → 韩信祠 → 金阙宫 → 原路返回",
        access: "石家庄市区驾车40分钟可达,公交亦可到达。",
        tips: "适合带小孩和老人,山顶餐饮齐全。门票约50元,索道单程30元。",
        gear: ["运动鞋", "1L 饮水", "防晒+遮阳帽", "现金/手机"],
        emergency: { local: "鹿泉区文旅局 0311-82286666", rescue: "抱犊寨景区 0311-82085555", general: "110 / 120" },
        gpxNote: "景区指示完备,无需GPX。",
        soundscape: { name: "山顶风铃", search: "wind chime mountain temple" },
        coords: { lon: 114.31, lat: 38.12 },
        lastUpdated: "2026-05-18"
    },
    {
        id: 4,
        name: "嶂石岩",
        location: "赞皇县",
        difficulty: "medium",
        difficultyLabel: "中等",
        duration: "full",
        durationLabel: "一日",
        distance: "10 km",
        elevation: "约 700 m",
        bestSeason: "5月-10月",
        seasonTags: ["spring", "summer", "autumn"],
        theme: { sky: ["#f3d4b8", "#d89a78"], far: "#c08060", mid: "#a0604a", near: "#5d3e2a", accent: "cliff", sun: "warm", primary: "#a0604a", soft: "#f0e0d4" },
        ratings: { stamina: 3, technical: 3, exposure: 4, retreat: 3, signal: 3 },
        techGrade: "T2",
        epithet: "嶂石听壁",
        poem: {
            title: "蜀道难(节)",
            author: "李白",
            dynasty: "唐",
            lines: ["连峰去天不盈尺", "枯松倒挂倚绝壁", "飞湍瀑流争喧豗", "砯崖转石万壑雷"],
            note: "嶂石赤壁层叠三栈,回音壁雷霆动地,正合谪仙人写蜀道之险。"
        },
        description: "“嶂石岩地貌”命名地,丹崖赤壁与原始森林交相辉映,是地质爱好者天堂。",
        features: [
            "中国三大丹霞地貌之一,地理教科书级标本",
            "'三栈环抱'独特结构,如同三层巨型阶梯",
            "回音壁可清晰听到6-7次回声,世界级声学奇观",
            "夏季气温比市区低5-8℃,被誉为'天然空调房'",
            "野生植物800余种,中药材爱好者天堂"
        ],
        waypoints: [
            { time: "08:00", name: "槐泉峪入口", elev: "700m", scene: "🌳", vista: "百年古槐+清泉,景区门头标志", note: "停车,购票" },
            { time: "09:00", name: "一栈到达点", elev: "950m", scene: "🧱", vista: "丹霞赤壁第一层,层理清晰如书页", note: "可遥望整个第一层赤壁" },
            { time: "10:30", name: "二栈·回音壁", elev: "1200m", scene: "📢", vista: "巨型半圆崖壁,声波回荡6-7次", note: "对崖大喊试回声!" },
            { time: "12:00", name: "圆通寺", elev: "1250m", scene: "🛕", vista: "悬崖上的小寺院,素斋飘香", note: "寺内有素斋,需提前预约" },
            { time: "14:00", name: "三栈·九女峰", elev: "1400m", scene: "🏔️", vista: "九座赤色石峰一字排开,如九女并立", note: "九座石峰一字排开" },
            { time: "15:30", name: "纸糊套原始林", elev: "1300m", scene: "🌲", vista: "原始次生林深处,蕨类层层叠叠", note: "穿越原始次生林" },
            { time: "17:00", name: "返回入口", elev: "700m", scene: "🚶", vista: "环线步道,沿途看不同角度赤壁", note: "走环线下山" }
        ],
        hiddenSpots: [
            "纸糊套深处有一棵千年古槐,需穿小路30分钟,树洞可容5人",
            "回音壁正下方崖底有一处'冰窖',盛夏温度8℃左右,可避暑",
            "夜间在二栈营地观星,几乎无光污染,是河北最佳观星点之一"
        ],
        photography: "丹霞地貌日出日落最佳,9-10月红叶+赤壁是大片首选。",
        food: "赞皇核桃宴、原村土布炖菜、嶂石岩野菜饼。",
        cuisine: {
            tagline: "丹崖之下,核桃林深处的乡野席",
            signature: { name: "赞皇核桃宴", icon: "🌰", price: "¥150-280/桌", desc: "核桃仁炒鸡丁、核桃酥饼、核桃豆腐、核桃糊…一桌九品,皆出本地千年核桃林,清香微甘" },
            snack:     { name: "嶂石岩野菜饼", icon: "🥬", price: "¥6-10/个", desc: "山韭菜+柳树芽+面糊烙制,带着初春青草味,登山者的天然维生素片" },
            drink:     { name: "土布村小米黄酒", icon: "🍶", price: "¥30/壶", desc: "原村土布村自酿,微甜带醇,温热下肚,五脏皆暖,慎喝多" },
            shop:      "推荐:原村土布村·土窑食堂 / 嶂石岩景区下·农家七大碗",
            seasonal:  { summer: "夏宜:野菜冷面 + 山泉冰镇核桃露", autumn: "秋宜:新核桃焖鸡 + 板栗烧鸡块" },
            tea:       "宜配:赞皇大枣茶,熬到枣肉化糖,温补养血",
            verse:     "「采采芣苡,薄言采之」 — 山野所馈,皆是诗经里的滋味"
        },
        route: "槐泉峪入口 → 一栈 → 二栈(回音壁) → 三栈(九女峰) → 圆通寺 → 下山",
        access: "石家庄出发车程约2.5小时,可经赞皇县城前往。",
        tips: "山路陡峭,部分路段需手脚并用,务必穿防滑徒步鞋。门票约65元。",
        gear: ["登山鞋(防滑)", "登山杖", "2L 饮水", "手套(攀爬)", "防晒+遮阳帽", "薄外套", "急救包"],
        emergency: { local: "赞皇文旅局 0311-84221234", rescue: "嶂石岩景区 0311-84272666", general: "110 / 120" },
        gpxNote: "建议下载景区地图,纸糊套段标识较少。",
        soundscape: { name: "瀑布回音", search: "waterfall canyon echo" },
        coords: { lon: 114.20, lat: 37.51 },
        lastUpdated: "2026-05-12"
    },
    {
        id: 5,
        name: "天桂山",
        location: "平山县",
        difficulty: "medium",
        difficultyLabel: "中等",
        duration: "full",
        durationLabel: "一日",
        distance: "9 km",
        elevation: "约 800 m",
        bestSeason: "秋季红叶最美",
        seasonTags: ["autumn"],
        theme: { sky: ["#ffd6a5", "#e89968"], far: "#d97a4f", mid: "#a85730", near: "#6a3520", accent: "maple", sun: "sunset", primary: "#c9402a", soft: "#f5d8c8" },
        ratings: { stamina: 3, technical: 2, exposure: 2, retreat: 4, signal: 3 },
        techGrade: "T2",
        epithet: "天桂醉枫",
        poem: {
            title: "山行",
            author: "杜牧",
            dynasty: "唐",
            lines: ["远上寒山石径斜", "白云生处有人家", "停车坐爱枫林晚", "霜叶红于二月花"],
            note: "天桂秋红甲冀州,杜牧此诗,简直为它而作。"
        },
        description: "有“北方桂林”之誉,集南秀北雄于一身,秋季漫山红叶宛如画卷。",
        features: [
            "明末崇祯帝行宫遗址,皇家气派",
            "石家庄秋季红叶第一山,黄栌+元宝枫双重色",
            "三百余处岩洞,银河洞、青龙洞各具特色",
            "电影《白毛女》故事原型地",
            "山体钟乳石与外景观结合,层次极丰富"
        ],
        waypoints: [
            { time: "08:30", name: "停车场", elev: "400m", scene: "🅿️", vista: "秋日红叶环绕停车场,金黄银杏夹道", note: "停车后走景区大道" },
            { time: "09:00", name: "真武殿", elev: "550m", scene: "⛩️", vista: "明代古建筑,殿前古柏苍劲石狮威严", note: "明代古建筑,殿外有古柏" },
            { time: "10:30", name: "青龙观", elev: "750m", scene: "🛕", vista: "悬崖上的道观,云雾飘渺如临仙境", note: "悬崖上的道观" },
            { time: "11:30", name: "三眼洞", elev: "780m", scene: "🕳️", vista: "三眼相通的天然溶洞,洞内幽深清凉", note: "需带手电,凉爽避暑" },
            { time: "13:00", name: "山顶素斋", elev: "850m", scene: "🍜", vista: "玄武峰下小餐馆,远山红叶为伴", note: "玄武峰下小餐馆" },
            { time: "14:30", name: "玄武峰主峰", elev: "1054m", scene: "🍁", vista: "海拔1054米360度全景,秋季漫山红叶如画", note: "360度全景" },
            { time: "16:00", name: "银河洞下山", elev: "500m", scene: "💧", vista: "洞内地下河,钟乳石滴水叮咚", note: "洞内有地下河,湿滑" }
        ],
        hiddenSpots: [
            "玄武峰东侧'白毛女洞'是电影原型场地,游客极少,洞内有当年留下的灶台遗迹",
            "10月下旬'红叶坪'红叶最盛,但需走非主路,问景区工人即可指路",
            "山下沕沕水生态风景区门票联票更划算,有北方少见的冰瀑(冬季)"
        ],
        photography: "10月15日-11月5日红叶高峰期,玄武峰俯拍漫山红色震撼。",
        food: "平山缸炉烧饼、压饸饹、天桂山板栗(秋季)。",
        cuisine: {
            tagline: "红叶山下,板栗飘香的秋日席",
            signature: { name: "天桂板栗烧鸡", icon: "🌰", price: "¥68-98", desc: "本地油栗+土鸡+冰糖红烧,栗肉粉糯吸饱鸡汁,是十月红叶季限定味道" },
            snack:     { name: "缸炉烧饼", icon: "🥯", price: "¥3-5", desc: "外焦芝麻香,夹鸡蛋火腿可作便携午餐,放包里两小时也酥脆" },
            drink:     { name: "山泉小米粥配腌萝卜", icon: "🥣", price: "¥8", desc: "玄武峰山泉水熬米,清凉透亮,配一碟自家腌萝卜片,清苦回甘" },
            shop:      "推荐:天桂山下·秋红农家院 / 沕沕水联游餐厅",
            seasonal:  { autumn: "秋宜:糖炒板栗 + 桂花酒(限定 10-11月)", winter: "冬宜:山菇炖羊肉 + 红薯粉条" },
            tea:       "宜配:野生山楂茶 / 山林秋蜜柚子茶",
            verse:     "「停车坐爱枫林晚,霜叶红于二月花」 — 杜牧若来,也要点一份板栗鸡"
        },
        route: "停车场 → 真武殿 → 青龙观 → 三眼洞 → 玄武峰主峰 → 银河洞下山",
        access: "石家庄→平山县城→天桂山,车程约2小时。",
        tips: "10月中下旬是赏红叶最佳时期,景区有索道可选。门票约65元。",
        gear: ["登山鞋", "登山杖", "2L 饮水", "手电(探洞)", "保暖衣(秋冬)", "干粮"],
        emergency: { local: "平山文旅局 0311-82911234", rescue: "天桂山景区 0311-82931666", general: "110 / 120" },
        gpxNote: "景区标识清晰,可不下载GPX。",
        soundscape: { name: "山林秋雨", search: "autumn rain forest leaves" },
        coords: { lon: 113.94, lat: 38.39 },
        lastUpdated: "2026-05-08"
    },
    {
        id: 6,
        name: "五岳寨",
        location: "灵寿县",
        difficulty: "medium",
        difficultyLabel: "中等",
        duration: "full",
        durationLabel: "一日",
        distance: "12 km",
        elevation: "约 900 m",
        bestSeason: "夏秋两季",
        seasonTags: ["summer", "autumn"],
        theme: { sky: ["#bdd9c4", "#5d8c6e"], far: "#6a9c7a", mid: "#3d6e50", near: "#1f4a30", accent: "five", sun: "warm", primary: "#3d6e50", soft: "#dde9e0" },
        ratings: { stamina: 4, technical: 2, exposure: 2, retreat: 4, signal: 3 },
        techGrade: "T2",
        epithet: "五岳凌云",
        poem: {
            title: "望岳",
            author: "杜甫",
            dynasty: "唐",
            lines: ["岱宗夫如何", "齐鲁青未了", "会当凌绝顶", "一览众山小"],
            note: "袖珍五岳,虽小而气魄不减,登顶时心胸自开。"
        },
        description: "因有五座奇峰似“五岳”而得名,森林覆盖率94%,是天然氧吧。",
        features: [
            "国家级森林公园,植被覆盖94%,负氧离子全省第一",
            "五座主峰各对应五岳,袖珍版'游遍五岳'体验",
            "高山草甸如绿毯,是华北少见的草原景观",
            "山间瀑布群,夏季水量大,可玩水戏水",
            "可缆车+徒步组合,强度可灵活调整"
        ],
        waypoints: [
            { time: "08:00", name: "景区正门", elev: "500m", scene: "🚪", vista: "森林公园大门,'天然氧吧'石碑醒目", note: "购票入园" },
            { time: "09:00", name: "飞瀑潭", elev: "700m", scene: "💦", vista: "瀑布飞泻入潭,水花四溅水雾凉爽", note: "可下水戏水,水温清凉" },
            { time: "10:30", name: "天梯入口", elev: "900m", scene: "🪜", vista: "近乎垂直的天然石梯,两侧密林", note: "近乎垂直的天然石梯" },
            { time: "12:00", name: "五岳主峰", elev: "1480m", scene: "🏔️", vista: "袖珍版'东岳'石碑+山脉延绵", note: "袖珍版'东岳'石碑" },
            { time: "13:30", name: "草甸午餐", elev: "1450m", scene: "🌾", vista: "高山草甸如绿毯,野花点点", note: "高山草甸野餐区" },
            { time: "15:30", name: "环山步道", elev: "1300m", scene: "🚶", vista: "经过其余四岳石碑,一路平缓林荫", note: "经过其余四岳石碑" },
            { time: "17:00", name: "缆车下山", elev: "500m", scene: "🚡", vista: "缆车上俯瞰整个森林公园,如阿尔卑斯", note: "缆车看风景一绝" }
        ],
        hiddenSpots: [
            "草甸东南方有一处'蘑菇坡',雨后秋天可采野蘑菇(注意识别)",
            "飞瀑潭上游500米有一处野温泉(温度温和),知道的人极少",
            "夜宿景区民宿可参与'山民夜话'活动,听老人讲当地传说"
        ],
        photography: "草甸黄昏色温极佳,缆车上俯拍可拍出阿尔卑斯感。",
        food: "灵寿腌肉、河北烩面、山菇炖鸡。",
        cuisine: {
            tagline: "森林氧吧旁,腌肉飘香的山民桌",
            signature: { name: "灵寿腌肉炖山菇", icon: "🥘", price: "¥58-88", desc: "祖传腌肉切片,与刚采的羊肚菌、口蘑同炖,菌香肉鲜,登山疲惫一扫而空" },
            snack:     { name: "灵寿手擀烩面", icon: "🍜", price: "¥18-25", desc: "面片宽厚耐嚼,羊汤打底,烫一把绿叶,撒一把香菜,大碗一口闷" },
            drink:     { name: "山间野花蜂蜜柠檬水", icon: "🍯", price: "¥10", desc: "本地槐花蜜兑山泉,加一片柠檬,登山补给的天然电解质" },
            shop:      "推荐:五岳寨景区·林间小院 / 灵寿县城·老烩面馆(车程 40 分钟)",
            seasonal:  { summer: "夏宜:野菌凉拌 + 山泉啤酒", autumn: "秋宜:新菇炖鸡 + 灵寿红枣糕" },
            tea:       "宜配:灵寿野生连翘茶,微苦清肝,登山者良伴",
            verse:     "「采菊东篱下,悠然见南山」 — 陶渊明此境,五岳寨民宿可得"
        },
        route: "正门 → 飞瀑潭 → 天梯 → 五岳主峰 → 草甸 → 缆车下山",
        access: "石家庄→灵寿→五岳寨,车程约2.5小时。",
        tips: "夏季是避暑佳地,建议早出发以便看云海。门票约65元。",
        gear: ["登山鞋", "登山杖", "2L 饮水", "速干衣", "防晒", "薄外套(高海拔)"],
        emergency: { local: "灵寿文旅局 0311-82581234", rescue: "五岳寨景区 0311-82581888", general: "110 / 120" },
        gpxNote: "建议下载景区地图,环山步道岔路较多。",
        soundscape: { name: "高山草甸鸟鸣", search: "alpine meadow birds breeze" },
        coords: { lon: 113.78, lat: 38.61 },
        lastUpdated: "2026-05-14"
    },
    {
        id: 7,
        name: "西柏坡 — 天台山环线",
        location: "平山县",
        difficulty: "easy",
        difficultyLabel: "轻松",
        duration: "half",
        durationLabel: "半日",
        distance: "5 km",
        elevation: "约 200 m",
        bestSeason: "全年适宜",
        seasonTags: ["spring", "summer", "autumn", "winter"],
        theme: { sky: ["#c8dde0", "#88a8b8"], far: "#88a896", mid: "#5a7c70", near: "#3a5648", accent: "lake", sun: "cool", primary: "#5a7c70", soft: "#dde6e3" },
        ratings: { stamina: 1, technical: 1, exposure: 1, retreat: 5, signal: 5 },
        techGrade: "T1",
        epithet: "西柏临湖",
        poem: {
            title: "饮湖上初晴后雨",
            author: "苏轼",
            dynasty: "宋",
            lines: ["水光潋滟晴方好", "山色空蒙雨亦奇", "欲把西湖比西子", "淡妆浓抹总相宜"],
            note: "岗南水库湖光山色,东坡此诗移此处亦相宜。"
        },
        description: "红色之旅与轻徒步结合,适合家庭周末出游,可顺便参观西柏坡纪念馆。",
        features: [
            "新中国'最后一个农村指挥所',爱国教育胜地",
            "岗南水库环抱,'山水+红色'双主题",
            "全程平缓,适合带老人小孩",
            "纪念馆免费,性价比极高",
            "周边农家乐成熟,吃住都方便"
        ],
        waypoints: [
            { time: "09:00", name: "纪念馆停车场", elev: "180m", scene: "🅿️", vista: "宽敞停车场,纪念碑高耸醒目", note: "停车后先参观纪念馆" },
            { time: "10:30", name: "中央旧址", elev: "200m", scene: "🏠", vista: "毛主席旧居小院,质朴砖墙木门", note: "参观毛主席旧居等" },
            { time: "12:00", name: "湖边农家午餐", elev: "180m", scene: "🍴", vista: "岗南水库边的农家小院,水库鱼飘香", note: "可吃岗南水库鱼" },
            { time: "13:30", name: "沿湖步道起点", elev: "180m", scene: "🌊", vista: "岗南水库浩瀚水面,远山连绵", note: "沿岗南水库步行" },
            { time: "15:00", name: "天台山观景台", elev: "380m", scene: "🌄", vista: "俯瞰整个水库,湖光山色尽收眼底", note: "俯瞰整个水库" },
            { time: "16:30", name: "返回停车场", elev: "180m", scene: "🚶", vista: "另一侧步道,夕阳水面波光粼粼", note: "可走另一侧步道" }
        ],
        hiddenSpots: [
            "西柏坡纪念馆背后有一条少有人走的'初心小径',连通几处旧址",
            "岗南水库西侧'渔家湾'是当地人吃鱼的地方,价格比景区便宜一半",
            "天台山顶有一座观星台(简易),夜晚可观银河,但需提前确认开放时间"
        ],
        photography: "黄昏时湖面与天台山倒影最美,可出大片。",
        food: "岗南水库鱼宴、平山小米饭、农家土鸡。",
        cuisine: {
            tagline: "革命老区的湖鲜,岗南水库的清欢",
            signature: { name: "岗南水库全鱼宴", icon: "🐟", price: "¥128-188", desc: "鱼头熬汤、鱼尾红烧、鱼身清蒸、鱼皮凉拌,一鱼四吃,水库野生鱼无土腥味" },
            snack:     { name: "平山小米饭 + 自制酱菜", icon: "🍚", price: "¥10", desc: "西柏坡当年的'胜利粮',碗里能站住筷子,配六样小菜,质朴中见深意" },
            drink:     { name: "农家土豆汤", icon: "🍲", price: "¥15", desc: "土豆+西红柿+鸡蛋,简单到令人感动,正是当年指挥所里的味道" },
            shop:      "推荐:岗南水库西·渔家湾 / 西柏坡村·五大书记纪念餐厅",
            seasonal:  { spring: "春宜:湖边野菜+柳树芽煎鸡蛋", summer: "夏宜:冰镇水库虾 + 凉拌鱼皮" },
            tea:       "宜配:平山玫瑰花茶 / 西柏坡红色文化纪念酒",
            verse:     "「水光潋滟晴方好」 — 东坡此句移此处,湖畔一席,胜过西湖宴"
        },
        route: "西柏坡纪念馆 → 中央旧址 → 沿湖步道 → 天台山观景台 → 返回",
        access: "石家庄出发车程约1.5小时,公共交通便利。",
        tips: "强烈建议结合参观爱国主义教育基地,纪念馆免费开放。",
        gear: ["舒适步行鞋", "1L 饮水", "防晒", "现金/手机"],
        emergency: { local: "平山文旅局 0311-82911234", rescue: "西柏坡景区 0311-82850000", general: "110 / 120" },
        gpxNote: "完全无需GPX。",
        soundscape: { name: "湖水拍岸", search: "lake waves shore nature" },
        coords: { lon: 113.96, lat: 38.32 },
        lastUpdated: "2026-05-16"
    },
    {
        id: 8,
        name: "藤龙山",
        location: "赞皇县",
        difficulty: "easy",
        difficultyLabel: "轻松",
        duration: "half",
        durationLabel: "半日",
        distance: "6 km",
        elevation: "约 400 m",
        bestSeason: "春夏两季",
        seasonTags: ["spring", "summer"],
        theme: { sky: ["#d4ebd8", "#95b89e"], far: "#7eb09b", mid: "#4a8c70", near: "#2d5a40", accent: "waterfall", sun: "warm", primary: "#4a8c70", soft: "#e0ebe3" },
        ratings: { stamina: 2, technical: 2, exposure: 3, retreat: 4, signal: 4 },
        techGrade: "T2",
        epithet: "藤龙听瀑",
        poem: {
            title: "庐山谣(节)",
            author: "李白",
            dynasty: "唐",
            lines: ["登高壮观天地间", "大江茫茫去不还", "黄云万里动风色", "白波九道流雪山"],
            note: "九瀑十八潭,飞泉如练,正合谪仙人观山观水之豪。"
        },
        description: "以亚洲最长的飞拉达和九瀑十八潭闻名,适合亲子徒步与轻量探险。",
        features: [
            "拥有亚洲最长飞拉达(攀岩铁道),3km岩壁体验",
            "九瀑十八潭水景丰富,夏季戏水首选",
            "原始藤蔓植物覆盖,'藤龙'之名由此",
            "玻璃栈道悬崖凌空,刺激度高",
            "可探险也可轻徒步,弹性大"
        ],
        waypoints: [
            { time: "08:30", name: "景区入口", elev: "500m", scene: "🌿", vista: "藤蔓缠绕的入口大门,飞拉达介绍牌", note: "购票,租赁装备(如玩飞拉达)" },
            { time: "09:00", name: "第一潭", elev: "550m", scene: "💧", vista: "清澈碧潭,藤蔓垂落水面波光", note: "拍照打卡点" },
            { time: "10:30", name: "沿溪步道", elev: "650m", scene: "🌉", vista: "穿溪过桥,木栈道蜿蜒入林", note: "穿溪过桥,景色丰富" },
            { time: "12:00", name: "九瀑顶", elev: "780m", scene: "💦", vista: "瀑布顶端俯瞰整个潭群,水声雷鸣", note: "潭水边休息用餐" },
            { time: "13:30", name: "玻璃栈道", elev: "800m", scene: "🪟", vista: "凌空透明栈道,脚下深谷令人腿软", note: "凌空高悬,体验刺激" },
            { time: "14:30", name: "飞拉达体验", elev: "750m", scene: "🧗", vista: "岩壁攀爬铁道,绝壁横移", note: "需有教练带" },
            { time: "16:00", name: "下山", elev: "500m", scene: "🌲", vista: "环线下山看不同藤蔓景观", note: "环线下山看不同景色" }
        ],
        hiddenSpots: [
            "景区深处'隐瀑'需走偏路20分钟,几乎无人,适合静心听水",
            "夏季'天然滑水道'是孩子最爱(注意安全,需穿戴整齐)",
            "山下'土窑院'民宿可体验石头房+柴火灶,完全乡村风情"
        ],
        photography: "瀑布慢门长曝光出片,需带三脚架与ND镜。",
        food: "赞皇枣糕、核桃宴、土窑烧饼。",
        cuisine: {
            tagline: "瀑布之下,枣林深处的甜与香",
            signature: { name: "赞皇大枣全席", icon: "🌰", price: "¥98-168", desc: "枣糕、枣酒、枣花蜜炖梨、红枣银耳羹、枣木熏鸡…赞皇千年大枣的九种打开方式" },
            snack:     { name: "土窑烧饼夹熏肉", icon: "🥪", price: "¥12-18", desc: "土窑烤的厚底烧饼,夹自家熏制猪头肉,口感对比强烈,登山归来一口爆汁" },
            drink:     { name: "山间果茶(枣+山楂+枸杞)", icon: "🍵", price: "¥10", desc: "本地三宝煮一锅,酸甜回甘,补气补血" },
            shop:      "推荐:土窑院民宿(石头房柴火灶) / 赞皇县城·枣乡食府",
            seasonal:  { spring: "春宜:槐花蒸饭 + 山泉饺子", summer: "夏宜:冰镇枣汁 + 凉皮" },
            tea:       "宜配:赞皇大枣红茶,煮到枣肉绵软,暖胃暖心",
            verse:     "「明月松间照,清泉石上流」 — 王维写水之境,藤龙瀑下亦得"
        },
        route: "景区入口 → 第一潭 → 沿溪步道 → 九瀑顶 → 玻璃栈道 → 下山",
        access: "石家庄→赞皇→藤龙山,车程约2小时。",
        tips: "夏季水量丰沛景色最佳,飞拉达需另行购票约150元。",
        gear: ["防滑徒步鞋", "速干衣", "1.5L 饮水", "防晒", "毛巾(戏水)", "手套(飞拉达)"],
        emergency: { local: "赞皇文旅局 0311-84221234", rescue: "藤龙山景区 0311-84273888", general: "110 / 120" },
        gpxNote: "景区线路清晰。",
        soundscape: { name: "山涧溪流", search: "stream creek mountain bamboo" },
        coords: { lon: 114.27, lat: 37.55 },
        lastUpdated: "2026-05-13"
    },
    {
        id: 9,
        name: "佛光山",
        location: "井陉县",
        difficulty: "hard",
        difficultyLabel: "困难",
        duration: "full",
        durationLabel: "一日",
        distance: "14 km",
        elevation: "约 1000 m",
        bestSeason: "秋季",
        seasonTags: ["autumn"],
        theme: { sky: ["#f0c89a", "#c89a6e"], far: "#8a8050", mid: "#5a6038", near: "#2d4a1f", accent: "ridge", sun: "sunset", primary: "#5a6038", soft: "#e8e0d0" },
        ratings: { stamina: 4, technical: 4, exposure: 5, retreat: 1, signal: 1 },
        techGrade: "T4",
        epithet: "佛光独行",
        poem: {
            title: "登幽州台歌",
            author: "陈子昂",
            dynasty: "唐",
            lines: ["前不见古人", "后不见来者", "念天地之悠悠", "独怆然而涕下"],
            note: "佛光山脊孤立无援,独行者方知天地之大,人之小,正合此千古绝唱。"
        },
        description: "未完全商业开发的徒步胜地,以原始山野景观吸引硬核驴友,需具备徒步经验。",
        features: [
            "未商业化的'野山',无门票无人挤",
            "山脊线徒步,视野开阔,适合穿越爱好者",
            "可顺穿天长古镇(秦皇古驿道遗迹)",
            "秋季层林尽染,但无人为修饰,纯原野美",
            "需自备饮水、补给与导航装备"
        ],
        waypoints: [
            { time: "07:00", name: "天长古镇集合", elev: "300m", scene: "🏘️", vista: "千年古镇石板路+古城墙,炊烟初起", note: "古道起点,补给最后机会" },
            { time: "08:00", name: "秦皇古道入口", elev: "400m", scene: "🛤️", vista: "秦代车辙印迹清晰可见,深陷石板", note: "石板车辙印迹清晰" },
            { time: "10:00", name: "山脊线起点", elev: "800m", scene: "⛰️", vista: "开阔山脊,视野极佳风过长草", note: "开始硬核徒步" },
            { time: "12:00", name: "佛光绝壁", elev: "1150m", scene: "🪨", vista: "崖顶午餐,脚下深谷云雾翻涌", note: "崖顶午餐,绝景" },
            { time: "14:30", name: "佛光顶", elev: "1290m", scene: "🌅", vista: "海拔1290米登顶,百里山色一览", note: "登顶,可见百里山色" },
            { time: "16:30", name: "西沟村", elev: "550m", scene: "🏡", vista: "山脚石头村落,炊烟袅袅升起", note: "村内有简易餐饮" },
            { time: "18:00", name: "包车返程", elev: "300m", scene: "🚐", vista: "村口包车点,夕阳挥别山野", note: "需提前联系当地车" }
        ],
        hiddenSpots: [
            "山脊中段有一片'红叶谷',9月底10月初无人涉足,色彩堪比黄山",
            "佛光顶北侧崖壁有摩崖石刻(年代不详),需绳降才能近距离观察",
            "西沟村李家老宅可吃到正宗'石磨豆腐宴',需提前一天电话预约"
        ],
        photography: "佛光顶日落+逆光人像极出片,但需要长焦镜头压缩远山。",
        food: "天长古镇缸炉烧饼、井陉煎饼、西沟石磨豆腐宴。",
        cuisine: {
            tagline: "野山归来,千年古道的一席素斋",
            signature: { name: "西沟石磨豆腐宴", icon: "🥢", price: "¥80-150", desc: "山间石磨现磨豆腐,做出豆腐脑、煎豆腐、酿豆腐、豆腐丸子十二样,清淡中见功夫,需提前一天电话预约" },
            snack:     { name: "缸炉烧饼夹咸菜", icon: "🥯", price: "¥5", desc: "硬核驴友的标配:轻、抗饿、不怕压。下山进村第一口,带着烟火气" },
            drink:     { name: "山泉煮土鸡蛋汤", icon: "🥚", price: "¥12", desc: "西沟山泉煮自家土鸡蛋,撒葱花淋香油,五分钟一锅,质朴到极致" },
            shop:      "推荐:西沟村·李家老宅(必须预约) / 天长古镇·秦皇古道食肆",
            seasonal:  { autumn: "秋宜:豆腐宴 + 山楂泡酒(秋采)", winter: "冬宜:全套豆腐锅 + 烤红薯" },
            tea:       "宜配:山间野生菊花茶,独行之后清心宁神",
            verse:     "「独坐幽篁里,弹琴复长啸」 — 王维独处之乐,豆腐宴可佐"
        },
        route: "井陉天长古镇 → 古道 → 山脊线 → 佛光顶 → 西沟村下撤",
        access: "需自驾至井陉,有路段路况较差。",
        tips: "户外经验不足者请勿单独前往,需准备充足饮水、干粮、地图与定位设备。",
        gear: ["高帮登山鞋", "登山杖", "3L 饮水", "充足干粮", "冲锋衣", "头灯", "急救包", "对讲机/卫星通讯", "GPS/离线地图", "保险/身份证"],
        emergency: { local: "井陉文旅局 0311-82021290", rescue: "井陉应急 0311-82038888", general: "110 / 120 / 蓝天救援 0311-87085222" },
        gpxNote: "强制要求下载GPX离线轨迹+离线地图,部分路段无信号。",
        soundscape: { name: "山脊孤风", search: "mountain ridge wind solitude" },
        coords: { lon: 114.13, lat: 38.04 },
        lastUpdated: "2026-05-09"
    }
];
