const routes = [
    {
        id: 1,
        name: "苍岩山",
        location: "井陉县",
        difficulty: "medium",
        difficultyLabel: "中等",
        duration: "full",
        durationLabel: "一日",
        distance: "8 km",
        elevation: "约 600 m",
        bestSeason: "春秋两季",
        seasonTags: ["spring", "autumn"],
        theme: { sky: ["#a8d5c1", "#6a9c89"], far: "#5a8c7a", mid: "#3d6e5a", near: "#1f4a3a", accent: "temple", sun: "warm", primary: "#3d6e5a", soft: "#e0ebe3" },
        ratings: { stamina: 3, technical: 2, exposure: 2, retreat: 5, signal: 4 },
        techGrade: "T2",
        epithet: "苍岩怀古",
        poem: {
            title: "终南别业(节)",
            author: "王维",
            dynasty: "唐",
            lines: ["中岁颇好道", "晚家南山陲", "行到水穷处", "坐看云起时"],
            note: "登苍岩,见桥楼殿凌空,正合王摩诘'坐看云起'之境。"
        },
        description: "国家5A级景区,以悬空寺、桥楼殿著称,自然景观与古建筑融为一体,适合家庭出游。",
        features: [
            "中国三大悬空寺之一,桥楼殿建在两山之间的天然石桥上",
            "《卧虎藏龙》《赤壁》取景地,电影感拉满",
            "佛、道、儒三教合一的古建筑群,文化厚度足",
            "山路虽长但台阶完备,腿脚一般也能完成"
        ],
        waypoints: [
            { time: "08:30", name: "景区南门", elev: "300m", scene: "🏞️", vista: "古朴牌坊门洞,两侧苍翠松柏夹道,清晨入园人少", note: "建议早到,避开旅游团" },
            { time: "09:15", name: "桥楼殿", elev: "560m", scene: "🏯", vista: "凌空横跨两崖的悬空殿,《卧虎藏龙》经典机位", note: "经典取景点,正面拍照最佳" },
            { time: "10:00", name: "福庆寺主殿", elev: "620m", scene: "⛩️", vista: "千年古刹红墙黛瓦,殿前古碑林立檀香袅袅", note: "可在此祈福,殿内有古碑" },
            { time: "11:30", name: "公主峰观景台", elev: "830m", scene: "🏔️", vista: "峡谷俯瞰全景,层峦叠嶂直至天际", note: "俯瞰整个景区峡谷" },
            { time: "13:00", name: "蝴蝶谷", elev: "650m", scene: "🦋", vista: "溪水潺潺花木扶疏,夏日蝴蝶成群飞舞", note: "自带午餐,溪边休息" },
            { time: "15:30", name: "返回南门", elev: "300m", scene: "🌲", vista: "下山林荫小道,夕阳穿林而过", note: "可走另一侧步道下山看不同景色" }
        ],
        hiddenSpots: [
            "桥楼殿下方有一处少人知的拍摄机位,需绕到对岸石阶,能拍到悬空寺与峡谷全景",
            "藏经楼后山小路通往一处明代碑刻,导游一般不带,但管理处询问可指路",
            "景区外2公里的于家石头村是石头建筑奇观,联游性价比超高"
        ],
        photography: "上午10点前桥楼殿正面有光、下午3点后福庆寺方向逆光剪影,适合人像。",
        food: "山下井陉抿须面、缸炉烧饼、井陉煎饼,推荐'天长古镇'内的老店。",
        cuisine: {
            tagline: "山下天长古镇,千年驿站的烟火",
            signature: { name: "井陉抿须面", icon: "🍜", price: "¥15-25", desc: "手搓荞麦面,过水冷拌或浇老汤,劲道带豆香,是车马劳顿后第一碗热乎" },
            snack:     { name: "缸炉烧饼", icon: "🥯", price: "¥3-5/个", desc: "黄泥缸壁烤就,外脆芝麻香,中夹咸甜两味,徒步包里塞两个续命" },
            drink:     { name: "井陉煎饼配豆腐脑", icon: "🥣", price: "¥10",   desc: "薄脆煎饼裹刚出锅嫩豆腐脑,胡椒油一淋,寒气尽散" },
            shop:      "推荐:天长古镇·王家老烧饼铺 / 西关刘家面馆(下山驾车 15 分钟)",
            seasonal:  { summer: "夏宜:荞麦凉面 + 自酿酸梅汤", winter: "冬宜:羊汤抿须 + 烫一壶老白干" },
            tea:       "宜配:本地连翘茶,微涩回甘,清燥解乏",
            verse:     "「日暮苍山远,寒舍犬吠归人」 — 一碗热面胜十里春风"
        },
        route: "景区南门入口 → 桥楼殿 → 福庆寺 → 公主峰 → 蝴蝶谷 → 原路返回",
        access: "石家庄市区出发,沿G5京昆高速→苍岩山出口,车程约2小时。",
        tips: "夏季注意防晒,景区台阶较多,建议穿登山鞋。门票约65元。",
        gear: ["登山鞋(防滑)", "1.5L 饮水", "防晒霜+遮阳帽", "薄外套", "干粮/能量棒", "现金/手机支付"],
        emergency: { local: "井陉文旅局 0311-82021290", rescue: "井陉景区救援 0311-82033555", general: "110 / 120" },
        gpxNote: "景区线路完备,无需GPX。如需可下载景区官方电子地图。",
        soundscape: { name: "古寺钟声", search: "temple bell mountain wind" },
        coords: { lon: 114.06, lat: 37.93 },
        lastUpdated: "2026-05-10"
    },
    {
        id: 2,
        name: "驼梁山",
        location: "平山县",
        difficulty: "hard",
        difficultyLabel: "困难",
        duration: "multi",
        durationLabel: "多日",
        distance: "15 km",
        elevation: "约 1200 m",
        bestSeason: "夏季避暑首选",
        seasonTags: ["summer"],
        theme: { sky: ["#c4dce8", "#7eb09b"], far: "#a8c4b8", mid: "#5a8c7a", near: "#2d5a3d", accent: "snow", sun: "cool", primary: "#5a8c7a", soft: "#dee9e5" },
        ratings: { stamina: 5, technical: 3, exposure: 3, retreat: 2, signal: 2 },
        techGrade: "T3",
        epithet: "驼梁望云",
        poem: {
            title: "望庐山瀑布",
            author: "李白",
            dynasty: "唐",
            lines: ["日照香炉生紫烟", "遥看瀑布挂前川", "飞流直下三千尺", "疑是银河落九天"],
            note: "驼梁瀑布群飞泻千仞,合谪仙人'银河九天'之气魄。"
        },
        description: "海拔2281米,为河北五大高峰之一,夏季平均气温19℃,有“三省一市最高峰”之称。",
        features: [
            "海拔2281m,晋冀两省界峰,登顶可一脚踏两省",
            "夏季气温19℃,堪比东北凉爽,被誉为'天然空调'",
            "森林覆盖率98%,空气负氧离子浓度极高",
            "云海+日出+银河三重奏,摄影圣地",
            "唯一一条可在山顶露营的路线,推荐徒步爱好者"
        ],
        waypoints: [
            { time: "Day1 09:00", name: "南台入口", elev: "1100m", scene: "🚪", vista: "高山入口牌坊,远山笼罩云雾", note: "购票、登记入山" },
            { time: "Day1 11:00", name: "飞来石", elev: "1500m", scene: "🪨", vista: "悬于崖边的天然奇石,孤峰耸立", note: "天然奇石,绝佳休息点" },
            { time: "Day1 14:00", name: "通天梁", elev: "1900m", scene: "🥾", vista: "陡峭石阶通天而上,两侧密林深锁", note: "陡坡路段,小心湿滑" },
            { time: "Day1 16:30", name: "云顶营地", elev: "2200m", scene: "⛺", vista: "草甸营地晚霞绚烂,帐篷点点", note: "扎营,看日落与星空" },
            { time: "Day2 04:30", name: "主峰看日出", elev: "2281m", scene: "🌅", vista: "云海翻涌+日出金光万丈,界峰标志石", note: "云海日出绝景" },
            { time: "Day2 07:00", name: "返回拔营", elev: "2200m", scene: "🎒", vista: "晨雾营地,远山仍藏云中", note: "整理装备" },
            { time: "Day2 12:00", name: "北坡下山", elev: "1300m", scene: "🌲", vista: "原始森林步道,松涛阵阵", note: "另一条线下撤看不同风景" }
        ],
        hiddenSpots: [
            "云顶营地东侧500米有一处无名草甸,基本无人涉足,夜观银河无光污染",
            "下山途中'瀑布群岔路'可绕至冰瀑(冬季)和野生猴群活动区",
            "山下'山炸店村'有藏族风格小院民宿,可寄存装备并提供热水洗浴"
        ],
        photography: "主峰云海最佳时机为日出后30分钟,雨后第二天云海概率90%。星空建议农历月初。",
        food: "山下平山农家菜:压饸饹、缸炉烧饼、平山黑猪肉炖小笨鸡。",
        cuisine: {
            tagline: "高山归来,平山农家土灶等你",
            signature: { name: "平山黑猪肉炖笨鸡", icon: "🍲", price: "¥80-120/份", desc: "土灶柴火慢炖三小时,黑猪带皮配跑山鸡,汤色金黄油润不腻,登顶之后第一锅热汤" },
            snack:     { name: "压饸饹", icon: "🍝", price: "¥18-25", desc: "莜麦面压制,浇骨头汤+辣椒油+腌韭花,登山后补碳水的山民秘籍" },
            drink:     { name: "山炸店小米粥", icon: "🍚", price: "¥5",  desc: "平山小米熬到米油泛黄,配一碟自家咸菜,胃壁瞬间被温柔包裹" },
            shop:      "推荐:山炸店村·老李家土灶(露营驴友补给地) / 驼梁山下·农家小院",
            seasonal:  { summer: "夏宜:凉调豆角丝 + 冰镇绿豆汤", winter: "冬宜:全套土灶锅 + 自酿地瓜烧" },
            tea:       "宜配:平山金莲花茶,高山所产,清热降火",
            verse:     "「莫笑农家腊酒浑,丰年留客足鸡豚」 — 陆游写此处,亦不为过"
        },
        route: "南台入口 → 飞来石 → 通天梁 → 主峰云顶 → 北坡下山 / 露营",
        access: "石家庄→平山→驼梁景区,车程约3.5小时,建议自驾。",
        tips: "高海拔地区昼夜温差大,即使夏季也需带保暖衣物。建议两日行程,可在景区或山下民宿住宿。",
        gear: ["登山鞋(高帮)", "登山杖", "3L 饮水", "防风冲锋衣", "保暖抓绒/羽绒", "帐篷+睡袋(露营)", "头灯", "急救包", "保险/身份证", "卫星通讯(强烈推荐)"],
        emergency: { local: "平山文旅局 0311-82911234", rescue: "驼梁景区救援 0311-82939999", general: "110 / 120 / 蓝天救援 0311-87085222" },
        gpxNote: "强烈建议下载 GPX 离线轨迹文件,山顶部分区域无信号。",
        soundscape: { name: "风过松林", search: "wind pine forest mountain" },
        coords: { lon: 113.59, lat: 38.74 },
        lastUpdated: "2026-05-15"
    },
    {
        id: 3,
        name: "抱犊寨",
        location: "鹿泉区",
        difficulty: "easy",
        difficultyLabel: "轻松",
        duration: "half",
        durationLabel: "半日",
        distance: "4 km",
        elevation: "约 300 m",
        bestSeason: "全年适宜",
        seasonTags: ["spring", "summer", "autumn", "winter"],
        theme: { sky: ["#d4e8d8", "#8bb89e"], far: "#7ea88e", mid: "#5a8c70", near: "#3a6e50", accent: "flat", sun: "warm", primary: "#5a8c70", soft: "#e3ede5" },
        ratings: { stamina: 1, technical: 1, exposure: 1, retreat: 5, signal: 5 },
        techGrade: "T1",
        epithet: "抱犊望平",
        poem: {
            title: "登抱犊寨",
            author: "苏轼(化用)",
            dynasty: "宋",
            lines: ["不识庐山真面目", "只缘身在此山中", "山顶平如台", "万里入襟胸"],
            note: "抱犊山顶平阔,登顶方知华北平原之辽阔。"
        },
        description: "距石家庄市区仅16公里,有“天下奇寨”美誉,山顶平坦广阔,可俯瞰华北平原。",
        features: [
            "市区16km,'最近的山',下午出发也来得及",
            "山顶平坦如运动场,占地600余亩,有'山顶平原'之奇",
            "韩信背水之战古战场遗址,历史厚重",
            "南北朝时期金阙宫为道教圣地,香火延续至今",
            "可缆车上下,亲子/老人完全无负担"
        ],
        waypoints: [
            { time: "13:30", name: "山下停车场", elev: "150m", scene: "🅿️", vista: "山下广场仰视'寨'字山顶,缆车索道斜跨", note: "停车免费,设施齐备" },
            { time: "13:50", name: "缆车站", elev: "180m", scene: "🚡", vista: "彩色缆车缓缓上升,俯瞰山下村庄绿野", note: "缆车7分钟直达山顶" },
            { time: "14:10", name: "南天门", elev: "450m", scene: "🏛️", vista: "明代古城墙巍然耸立,'南天门'三字苍劲", note: "山顶入口,有古城墙" },
            { time: "14:40", name: "韩信祠", elev: "460m", scene: "⛩️", vista: "祠内壁画讲述背水一战,古朴庄重", note: "祠内有韩信生平壁画" },
            { time: "15:30", name: "金阙宫", elev: "455m", scene: "🛕", vista: "金顶道观在阳光下熠熠生辉,香烟缭绕", note: "石家庄最大道观,可上香" },
            { time: "16:30", name: "环山步道", elev: "440m", scene: "🌅", vista: "山顶平原步道,夕阳将云霞染红", note: "绕山顶一圈看夕阳" },
            { time: "17:30", name: "下山", elev: "150m", scene: "🚡", vista: "缆车下山华北平原一览无余", note: "可走步道或缆车" }
        ],
        hiddenSpots: [
            "西侧'天井'是天然下凹平台,游客极少,可坐看华北平原日落",
            "万亩柏林深处有'求子洞'石窟,需问当地人才能找到",
            "山下东沟村有正宗的'抱犊寨石锅鸡',是本地人才知道的下山饭"
        ],
        photography: "傍晚17点后金阙宫琉璃瓦在夕阳下金光闪闪,人少景美。",
        food: "鹿泉肉饼、抱犊寨石锅鸡、华北油面茶。",
        cuisine: {
            tagline: "市区最近的山,有市区最方便的味",
            signature: { name: "抱犊寨石锅鸡", icon: "🍳", price: "¥98-158", desc: "麦饭石锅高温焗鸡,鸡皮焦脆肉嫩出油,鸡油里炖香菇豆腐,是本地人才知道的下山仪式" },
            snack:     { name: "鹿泉肉饼", icon: "🥟", price: "¥10-15/个", desc: "面皮薄如蝉翼,牛肉葱油填满每个褶,咬下去汁水四溢,刚出锅烫嘴最香" },
            drink:     { name: "油面茶", icon: "☕", price: "¥6",   desc: "炒小麦粉调糊,撒芝麻花生,华北早点之王,徒步前后皆宜" },
            shop:      "推荐:东沟村·老石锅 / 鹿泉北街·二刘肉饼(车程 10-15 分钟)",
            seasonal:  { spring: "春宜:嫩荠菜煎饼 + 香椿摊蛋", autumn: "秋宜:山下柿饼 + 新榨核桃油凉面" },
            tea:       "宜配:本地金银花茶 / 华北米酒(就石锅鸡尤佳)",
            verse:     "「半亩方塘一鉴开,天光云影共徘徊」 — 山顶饱览天地,山下饱览一锅"
        },
        route: "停车场 → 步道上山(或缆车) → 南天门 → 韩信祠 → 金阙宫 → 原路返回",
        access: "石家庄市区驾车40分钟可达,公交亦可到达。",
        tips: "适合带小孩和老人,山顶餐饮齐全。门票约50元,索道单程30元。",
        gear: ["运动鞋", "1L 饮水", "防晒+遮阳帽", "现金/手机"],
        emergency: { local: "鹿泉区文旅局 0311-82286666", rescue: "抱犊寨景区 0311-82085555", general: "110 / 120" },
        gpxNote: "景区指示完备,无需GPX。",
        soundscape: { name: "山顶风铃", search: "wind chime mountain temple" },
        coords: { lon: 114.31, lat: 38.12 },
        lastUpdated: "2026-05-18"
    },
    {
        id: 4,
        name: "嶂石岩",
        location: "赞皇县",
        difficulty: "medium",
        difficultyLabel: "中等",
        duration: "full",
        durationLabel: "一日",
        distance: "10 km",
        elevation: "约 700 m",
        bestSeason: "5月-10月",
        seasonTags: ["spring", "summer", "autumn"],
        theme: { sky: ["#f3d4b8", "#d89a78"], far: "#c08060", mid: "#a0604a", near: "#5d3e2a", accent: "cliff", sun: "warm", primary: "#a0604a", soft: "#f0e0d4" },
        ratings: { stamina: 3, technical: 3, exposure: 4, retreat: 3, signal: 3 },
        techGrade: "T2",
        epithet: "嶂石听壁",
        poem: {
            title: "蜀道难(节)",
            author: "李白",
            dynasty: "唐",
            lines: ["连峰去天不盈尺", "枯松倒挂倚绝壁", "飞湍瀑流争喧豗", "砯崖转石万壑雷"],
            note: "嶂石赤壁层叠三栈,回音壁雷霆动地,正合谪仙人写蜀道之险。"
        },
        description: "“嶂石岩地貌”命名地,丹崖赤壁与原始森林交相辉映,是地质爱好者天堂。",
        features: [
            "中国三大丹霞地貌之一,地理教科书级标本",
            "'三栈环抱'独特结构,如同三层巨型阶梯",
            "回音壁可清晰听到6-7次回声,世界级声学奇观",
            "夏季气温比市区低5-8℃,被誉为'天然空调房'",
            "野生植物800余种,中药材爱好者天堂"
        ],
        waypoints: [
            { time: "08:00", name: "槐泉峪入口", elev: "700m", scene: "🌳", vista: "百年古槐+清泉,景区门头标志", note: "停车,购票" },
            { time: "09:00", name: "一栈到达点", elev: "950m", scene: "🧱", vista: "丹霞赤壁第一层,层理清晰如书页", note: "可遥望整个第一层赤壁" },
            { time: "10:30", name: "二栈·回音壁", elev: "1200m", scene: "📢", vista: "巨型半圆崖壁,声波回荡6-7次", note: "对崖大喊试回声!" },
            { time: "12:00", name: "圆通寺", elev: "1250m", scene: "🛕", vista: "悬崖上的小寺院,素斋飘香", note: "寺内有素斋,需提前预约" },
            { time: "14:00", name: "三栈·九女峰", elev: "1400m", scene: "🏔️", vista: "九座赤色石峰一字排开,如九女并立", note: "九座石峰一字排开" },
            { time: "15:30", name: "纸糊套原始林", elev: "1300m", scene: "🌲", vista: "原始次生林深处,蕨类层层叠叠", note: "穿越原始次生林" },
            { time: "17:00", name: "返回入口", elev: "700m", scene: "🚶", vista: "环线步道,沿途看不同角度赤壁", note: "走环线下山" }
        ],
        hiddenSpots: [
            "纸糊套深处有一棵千年古槐,需穿小路30分钟,树洞可容5人",
            "回音壁正下方崖底有一处'冰窖',盛夏温度8℃左右,可避暑",
            "夜间在二栈营地观星,几乎无光污染,是河北最佳观星点之一"
        ],
        photography: "丹霞地貌日出日落最佳,9-10月红叶+赤壁是大片首选。",
        food: "赞皇核桃宴、原村土布炖菜、嶂石岩野菜饼。",
        cuisine: {
            tagline: "丹崖之下,核桃林深处的乡野席",
            signature: { name: "赞皇核桃宴", icon: "🌰", price: "¥150-280/桌", desc: "核桃仁炒鸡丁、核桃酥饼、核桃豆腐、核桃糊…一桌九品,皆出本地千年核桃林,清香微甘" },
            snack:     { name: "嶂石岩野菜饼", icon: "🥬", price: "¥6-10/个", desc: "山韭菜+柳树芽+面糊烙制,带着初春青草味,登山者的天然维生素片" },
            drink:     { name: "土布村小米黄酒", icon: "🍶", price: "¥30/壶", desc: "原村土布村自酿,微甜带醇,温热下肚,五脏皆暖,慎喝多" },
            shop:      "推荐:原村土布村·土窑食堂 / 嶂石岩景区下·农家七大碗",
            seasonal:  { summer: "夏宜:野菜冷面 + 山泉冰镇核桃露", autumn: "秋宜:新核桃焖鸡 + 板栗烧鸡块" },
            tea:       "宜配:赞皇大枣茶,熬到枣肉化糖,温补养血",
            verse:     "「采采芣苡,薄言采之」 — 山野所馈,皆是诗经里的滋味"
        },
        route: "槐泉峪入口 → 一栈 → 二栈(回音壁) → 三栈(九女峰) → 圆通寺 → 下山",
        access: "石家庄出发车程约2.5小时,可经赞皇县城前往。",
        tips: "山路陡峭,部分路段需手脚并用,务必穿防滑徒步鞋。门票约65元。",
        gear: ["登山鞋(防滑)", "登山杖", "2L 饮水", "手套(攀爬)", "防晒+遮阳帽", "薄外套", "急救包"],
        emergency: { local: "赞皇文旅局 0311-84221234", rescue: "嶂石岩景区 0311-84272666", general: "110 / 120" },
        gpxNote: "建议下载景区地图,纸糊套段标识较少。",
        soundscape: { name: "瀑布回音", search: "waterfall canyon echo" },
        coords: { lon: 114.20, lat: 37.51 },
        lastUpdated: "2026-05-12"
    },
    {
        id: 5,
        name: "天桂山",
        location: "平山县",
        difficulty: "medium",
        difficultyLabel: "中等",
        duration: "full",
        durationLabel: "一日",
        distance: "9 km",
        elevation: "约 800 m",
        bestSeason: "秋季红叶最美",
        seasonTags: ["autumn"],
        theme: { sky: ["#ffd6a5", "#e89968"], far: "#d97a4f", mid: "#a85730", near: "#6a3520", accent: "maple", sun: "sunset", primary: "#c9402a", soft: "#f5d8c8" },
        ratings: { stamina: 3, technical: 2, exposure: 2, retreat: 4, signal: 3 },
        techGrade: "T2",
        epithet: "天桂醉枫",
        poem: {
            title: "山行",
            author: "杜牧",
            dynasty: "唐",
            lines: ["远上寒山石径斜", "白云生处有人家", "停车坐爱枫林晚", "霜叶红于二月花"],
            note: "天桂秋红甲冀州,杜牧此诗,简直为它而作。"
        },
        description: "有“北方桂林”之誉,集南秀北雄于一身,秋季漫山红叶宛如画卷。",
        features: [
            "明末崇祯帝行宫遗址,皇家气派",
            "石家庄秋季红叶第一山,黄栌+元宝枫双重色",
            "三百余处岩洞,银河洞、青龙洞各具特色",
            "电影《白毛女》故事原型地",
            "山体钟乳石与外景观结合,层次极丰富"
        ],
        waypoints: [
            { time: "08:30", name: "停车场", elev: "400m", scene: "🅿️", vista: "秋日红叶环绕停车场,金黄银杏夹道", note: "停车后走景区大道" },
            { time: "09:00", name: "真武殿", elev: "550m", scene: "⛩️", vista: "明代古建筑,殿前古柏苍劲石狮威严", note: "明代古建筑,殿外有古柏" },
            { time: "10:30", name: "青龙观", elev: "750m", scene: "🛕", vista: "悬崖上的道观,云雾飘渺如临仙境", note: "悬崖上的道观" },
            { time: "11:30", name: "三眼洞", elev: "780m", scene: "🕳️", vista: "三眼相通的天然溶洞,洞内幽深清凉", note: "需带手电,凉爽避暑" },
            { time: "13:00", name: "山顶素斋", elev: "850m", scene: "🍜", vista: "玄武峰下小餐馆,远山红叶为伴", note: "玄武峰下小餐馆" },
            { time: "14:30", name: "玄武峰主峰", elev: "1054m", scene: "🍁", vista: "海拔1054米360度全景,秋季漫山红叶如画", note: "360度全景" },
            { time: "16:00", name: "银河洞下山", elev: "500m", scene: "💧", vista: "洞内地下河,钟乳石滴水叮咚", note: "洞内有地下河,湿滑" }
        ],
        hiddenSpots: [
            "玄武峰东侧'白毛女洞'是电影原型场地,游客极少,洞内有当年留下的灶台遗迹",
            "10月下旬'红叶坪'红叶最盛,但需走非主路,问景区工人即可指路",
            "山下沕沕水生态风景区门票联票更划算,有北方少见的冰瀑(冬季)"
        ],
        photography: "10月15日-11月5日红叶高峰期,玄武峰俯拍漫山红色震撼。",
        food: "平山缸炉烧饼、压饸饹、天桂山板栗(秋季)。",
        cuisine: {
            tagline: "红叶山下,板栗飘香的秋日席",
            signature: { name: "天桂板栗烧鸡", icon: "🌰", price: "¥68-98", desc: "本地油栗+土鸡+冰糖红烧,栗肉粉糯吸饱鸡汁,是十月红叶季限定味道" },
            snack:     { name: "缸炉烧饼", icon: "🥯", price: "¥3-5", desc: "外焦芝麻香,夹鸡蛋火腿可作便携午餐,放包里两小时也酥脆" },
            drink:     { name: "山泉小米粥配腌萝卜", icon: "🥣", price: "¥8", desc: "玄武峰山泉水熬米,清凉透亮,配一碟自家腌萝卜片,清苦回甘" },
            shop:      "推荐:天桂山下·秋红农家院 / 沕沕水联游餐厅",
            seasonal:  { autumn: "秋宜:糖炒板栗 + 桂花酒(限定 10-11月)", winter: "冬宜:山菇炖羊肉 + 红薯粉条" },
            tea:       "宜配:野生山楂茶 / 山林秋蜜柚子茶",
            verse:     "「停车坐爱枫林晚,霜叶红于二月花」 — 杜牧若来,也要点一份板栗鸡"
        },
        route: "停车场 → 真武殿 → 青龙观 → 三眼洞 → 玄武峰主峰 → 银河洞下山",
        access: "石家庄→平山县城→天桂山,车程约2小时。",
        tips: "10月中下旬是赏红叶最佳时期,景区有索道可选。门票约65元。",
        gear: ["登山鞋", "登山杖", "2L 饮水", "手电(探洞)", "保暖衣(秋冬)", "干粮"],
        emergency: { local: "平山文旅局 0311-82911234", rescue: "天桂山景区 0311-82931666", general: "110 / 120" },
        gpxNote: "景区标识清晰,可不下载GPX。",
        soundscape: { name: "山林秋雨", search: "autumn rain forest leaves" },
        coords: { lon: 113.94, lat: 38.39 },
        lastUpdated: "2026-05-08"
    },
    {
        id: 6,
        name: "五岳寨",
        location: "灵寿县",
        difficulty: "medium",
        difficultyLabel: "中等",
        duration: "full",
        durationLabel: "一日",
        distance: "12 km",
        elevation: "约 900 m",
        bestSeason: "夏秋两季",
        seasonTags: ["summer", "autumn"],
        theme: { sky: ["#bdd9c4", "#5d8c6e"], far: "#6a9c7a", mid: "#3d6e50", near: "#1f4a30", accent: "five", sun: "warm", primary: "#3d6e50", soft: "#dde9e0" },
        ratings: { stamina: 4, technical: 2, exposure: 2, retreat: 4, signal: 3 },
        techGrade: "T2",
        epithet: "五岳凌云",
        poem: {
            title: "望岳",
            author: "杜甫",
            dynasty: "唐",
            lines: ["岱宗夫如何", "齐鲁青未了", "会当凌绝顶", "一览众山小"],
            note: "袖珍五岳,虽小而气魄不减,登顶时心胸自开。"
        },
        description: "因有五座奇峰似“五岳”而得名,森林覆盖率94%,是天然氧吧。",
        features: [
            "国家级森林公园,植被覆盖94%,负氧离子全省第一",
            "五座主峰各对应五岳,袖珍版'游遍五岳'体验",
            "高山草甸如绿毯,是华北少见的草原景观",
            "山间瀑布群,夏季水量大,可玩水戏水",
            "可缆车+徒步组合,强度可灵活调整"
        ],
        waypoints: [
            { time: "08:00", name: "景区正门", elev: "500m", scene: "🚪", vista: "森林公园大门,'天然氧吧'石碑醒目", note: "购票入园" },
            { time: "09:00", name: "飞瀑潭", elev: "700m", scene: "💦", vista: "瀑布飞泻入潭,水花四溅水雾凉爽", note: "可下水戏水,水温清凉" },
            { time: "10:30", name: "天梯入口", elev: "900m", scene: "🪜", vista: "近乎垂直的天然石梯,两侧密林", note: "近乎垂直的天然石梯" },
            { time: "12:00", name: "五岳主峰", elev: "1480m", scene: "🏔️", vista: "袖珍版'东岳'石碑+山脉延绵", note: "袖珍版'东岳'石碑" },
            { time: "13:30", name: "草甸午餐", elev: "1450m", scene: "🌾", vista: "高山草甸如绿毯,野花点点", note: "高山草甸野餐区" },
            { time: "15:30", name: "环山步道", elev: "1300m", scene: "🚶", vista: "经过其余四岳石碑,一路平缓林荫", note: "经过其余四岳石碑" },
            { time: "17:00", name: "缆车下山", elev: "500m", scene: "🚡", vista: "缆车上俯瞰整个森林公园,如阿尔卑斯", note: "缆车看风景一绝" }
        ],
        hiddenSpots: [
            "草甸东南方有一处'蘑菇坡',雨后秋天可采野蘑菇(注意识别)",
            "飞瀑潭上游500米有一处野温泉(温度温和),知道的人极少",
            "夜宿景区民宿可参与'山民夜话'活动,听老人讲当地传说"
        ],
        photography: "草甸黄昏色温极佳,缆车上俯拍可拍出阿尔卑斯感。",
        food: "灵寿腌肉、河北烩面、山菇炖鸡。",
        cuisine: {
            tagline: "森林氧吧旁,腌肉飘香的山民桌",
            signature: { name: "灵寿腌肉炖山菇", icon: "🥘", price: "¥58-88", desc: "祖传腌肉切片,与刚采的羊肚菌、口蘑同炖,菌香肉鲜,登山疲惫一扫而空" },
            snack:     { name: "灵寿手擀烩面", icon: "🍜", price: "¥18-25", desc: "面片宽厚耐嚼,羊汤打底,烫一把绿叶,撒一把香菜,大碗一口闷" },
            drink:     { name: "山间野花蜂蜜柠檬水", icon: "🍯", price: "¥10", desc: "本地槐花蜜兑山泉,加一片柠檬,登山补给的天然电解质" },
            shop:      "推荐:五岳寨景区·林间小院 / 灵寿县城·老烩面馆(车程 40 分钟)",
            seasonal:  { summer: "夏宜:野菌凉拌 + 山泉啤酒", autumn: "秋宜:新菇炖鸡 + 灵寿红枣糕" },
            tea:       "宜配:灵寿野生连翘茶,微苦清肝,登山者良伴",
            verse:     "「采菊东篱下,悠然见南山」 — 陶渊明此境,五岳寨民宿可得"
        },
        route: "正门 → 飞瀑潭 → 天梯 → 五岳主峰 → 草甸 → 缆车下山",
        access: "石家庄→灵寿→五岳寨,车程约2.5小时。",
        tips: "夏季是避暑佳地,建议早出发以便看云海。门票约65元。",
        gear: ["登山鞋", "登山杖", "2L 饮水", "速干衣", "防晒", "薄外套(高海拔)"],
        emergency: { local: "灵寿文旅局 0311-82581234", rescue: "五岳寨景区 0311-82581888", general: "110 / 120" },
        gpxNote: "建议下载景区地图,环山步道岔路较多。",
        soundscape: { name: "高山草甸鸟鸣", search: "alpine meadow birds breeze" },
        coords: { lon: 113.78, lat: 38.61 },
        lastUpdated: "2026-05-14"
    },
    {
        id: 7,
        name: "西柏坡 — 天台山环线",
        location: "平山县",
        difficulty: "easy",
        difficultyLabel: "轻松",
        duration: "half",
        durationLabel: "半日",
        distance: "5 km",
        elevation: "约 200 m",
        bestSeason: "全年适宜",
        seasonTags: ["spring", "summer", "autumn", "winter"],
        theme: { sky: ["#c8dde0", "#88a8b8"], far: "#88a896", mid: "#5a7c70", near: "#3a5648", accent: "lake", sun: "cool", primary: "#5a7c70", soft: "#dde6e3" },
        ratings: { stamina: 1, technical: 1, exposure: 1, retreat: 5, signal: 5 },
        techGrade: "T1",
        epithet: "西柏临湖",
        poem: {
            title: "饮湖上初晴后雨",
            author: "苏轼",
            dynasty: "宋",
            lines: ["水光潋滟晴方好", "山色空蒙雨亦奇", "欲把西湖比西子", "淡妆浓抹总相宜"],
            note: "岗南水库湖光山色,东坡此诗移此处亦相宜。"
        },
        description: "红色之旅与轻徒步结合,适合家庭周末出游,可顺便参观西柏坡纪念馆。",
        features: [
            "新中国'最后一个农村指挥所',爱国教育胜地",
            "岗南水库环抱,'山水+红色'双主题",
            "全程平缓,适合带老人小孩",
            "纪念馆免费,性价比极高",
            "周边农家乐成熟,吃住都方便"
        ],
        waypoints: [
            { time: "09:00", name: "纪念馆停车场", elev: "180m", scene: "🅿️", vista: "宽敞停车场,纪念碑高耸醒目", note: "停车后先参观纪念馆" },
            { time: "10:30", name: "中央旧址", elev: "200m", scene: "🏠", vista: "毛主席旧居小院,质朴砖墙木门", note: "参观毛主席旧居等" },
            { time: "12:00", name: "湖边农家午餐", elev: "180m", scene: "🍴", vista: "岗南水库边的农家小院,水库鱼飘香", note: "可吃岗南水库鱼" },
            { time: "13:30", name: "沿湖步道起点", elev: "180m", scene: "🌊", vista: "岗南水库浩瀚水面,远山连绵", note: "沿岗南水库步行" },
            { time: "15:00", name: "天台山观景台", elev: "380m", scene: "🌄", vista: "俯瞰整个水库,湖光山色尽收眼底", note: "俯瞰整个水库" },
            { time: "16:30", name: "返回停车场", elev: "180m", scene: "🚶", vista: "另一侧步道,夕阳水面波光粼粼", note: "可走另一侧步道" }
        ],
        hiddenSpots: [
            "西柏坡纪念馆背后有一条少有人走的'初心小径',连通几处旧址",
            "岗南水库西侧'渔家湾'是当地人吃鱼的地方,价格比景区便宜一半",
            "天台山顶有一座观星台(简易),夜晚可观银河,但需提前确认开放时间"
        ],
        photography: "黄昏时湖面与天台山倒影最美,可出大片。",
        food: "岗南水库鱼宴、平山小米饭、农家土鸡。",
        cuisine: {
            tagline: "革命老区的湖鲜,岗南水库的清欢",
            signature: { name: "岗南水库全鱼宴", icon: "🐟", price: "¥128-188", desc: "鱼头熬汤、鱼尾红烧、鱼身清蒸、鱼皮凉拌,一鱼四吃,水库野生鱼无土腥味" },
            snack:     { name: "平山小米饭 + 自制酱菜", icon: "🍚", price: "¥10", desc: "西柏坡当年的'胜利粮',碗里能站住筷子,配六样小菜,质朴中见深意" },
            drink:     { name: "农家土豆汤", icon: "🍲", price: "¥15", desc: "土豆+西红柿+鸡蛋,简单到令人感动,正是当年指挥所里的味道" },
            shop:      "推荐:岗南水库西·渔家湾 / 西柏坡村·五大书记纪念餐厅",
            seasonal:  { spring: "春宜:湖边野菜+柳树芽煎鸡蛋", summer: "夏宜:冰镇水库虾 + 凉拌鱼皮" },
            tea:       "宜配:平山玫瑰花茶 / 西柏坡红色文化纪念酒",
            verse:     "「水光潋滟晴方好」 — 东坡此句移此处,湖畔一席,胜过西湖宴"
        },
        route: "西柏坡纪念馆 → 中央旧址 → 沿湖步道 → 天台山观景台 → 返回",
        access: "石家庄出发车程约1.5小时,公共交通便利。",
        tips: "强烈建议结合参观爱国主义教育基地,纪念馆免费开放。",
        gear: ["舒适步行鞋", "1L 饮水", "防晒", "现金/手机"],
        emergency: { local: "平山文旅局 0311-82911234", rescue: "西柏坡景区 0311-82850000", general: "110 / 120" },
        gpxNote: "完全无需GPX。",
        soundscape: { name: "湖水拍岸", search: "lake waves shore nature" },
        coords: { lon: 113.96, lat: 38.32 },
        lastUpdated: "2026-05-16"
    },
    {
        id: 8,
        name: "藤龙山",
        location: "赞皇县",
        difficulty: "easy",
        difficultyLabel: "轻松",
        duration: "half",
        durationLabel: "半日",
        distance: "6 km",
        elevation: "约 400 m",
        bestSeason: "春夏两季",
        seasonTags: ["spring", "summer"],
        theme: { sky: ["#d4ebd8", "#95b89e"], far: "#7eb09b", mid: "#4a8c70", near: "#2d5a40", accent: "waterfall", sun: "warm", primary: "#4a8c70", soft: "#e0ebe3" },
        ratings: { stamina: 2, technical: 2, exposure: 3, retreat: 4, signal: 4 },
        techGrade: "T2",
        epithet: "藤龙听瀑",
        poem: {
            title: "庐山谣(节)",
            author: "李白",
            dynasty: "唐",
            lines: ["登高壮观天地间", "大江茫茫去不还", "黄云万里动风色", "白波九道流雪山"],
            note: "九瀑十八潭,飞泉如练,正合谪仙人观山观水之豪。"
        },
        description: "以亚洲最长的飞拉达和九瀑十八潭闻名,适合亲子徒步与轻量探险。",
        features: [
            "拥有亚洲最长飞拉达(攀岩铁道),3km岩壁体验",
            "九瀑十八潭水景丰富,夏季戏水首选",
            "原始藤蔓植物覆盖,'藤龙'之名由此",
            "玻璃栈道悬崖凌空,刺激度高",
            "可探险也可轻徒步,弹性大"
        ],
        waypoints: [
            { time: "08:30", name: "景区入口", elev: "500m", scene: "🌿", vista: "藤蔓缠绕的入口大门,飞拉达介绍牌", note: "购票,租赁装备(如玩飞拉达)" },
            { time: "09:00", name: "第一潭", elev: "550m", scene: "💧", vista: "清澈碧潭,藤蔓垂落水面波光", note: "拍照打卡点" },
            { time: "10:30", name: "沿溪步道", elev: "650m", scene: "🌉", vista: "穿溪过桥,木栈道蜿蜒入林", note: "穿溪过桥,景色丰富" },
            { time: "12:00", name: "九瀑顶", elev: "780m", scene: "💦", vista: "瀑布顶端俯瞰整个潭群,水声雷鸣", note: "潭水边休息用餐" },
            { time: "13:30", name: "玻璃栈道", elev: "800m", scene: "🪟", vista: "凌空透明栈道,脚下深谷令人腿软", note: "凌空高悬,体验刺激" },
            { time: "14:30", name: "飞拉达体验", elev: "750m", scene: "🧗", vista: "岩壁攀爬铁道,绝壁横移", note: "需有教练带" },
            { time: "16:00", name: "下山", elev: "500m", scene: "🌲", vista: "环线下山看不同藤蔓景观", note: "环线下山看不同景色" }
        ],
        hiddenSpots: [
            "景区深处'隐瀑'需走偏路20分钟,几乎无人,适合静心听水",
            "夏季'天然滑水道'是孩子最爱(注意安全,需穿戴整齐)",
            "山下'土窑院'民宿可体验石头房+柴火灶,完全乡村风情"
        ],
        photography: "瀑布慢门长曝光出片,需带三脚架与ND镜。",
        food: "赞皇枣糕、核桃宴、土窑烧饼。",
        cuisine: {
            tagline: "瀑布之下,枣林深处的甜与香",
            signature: { name: "赞皇大枣全席", icon: "🌰", price: "¥98-168", desc: "枣糕、枣酒、枣花蜜炖梨、红枣银耳羹、枣木熏鸡…赞皇千年大枣的九种打开方式" },
            snack:     { name: "土窑烧饼夹熏肉", icon: "🥪", price: "¥12-18", desc: "土窑烤的厚底烧饼,夹自家熏制猪头肉,口感对比强烈,登山归来一口爆汁" },
            drink:     { name: "山间果茶(枣+山楂+枸杞)", icon: "🍵", price: "¥10", desc: "本地三宝煮一锅,酸甜回甘,补气补血" },
            shop:      "推荐:土窑院民宿(石头房柴火灶) / 赞皇县城·枣乡食府",
            seasonal:  { spring: "春宜:槐花蒸饭 + 山泉饺子", summer: "夏宜:冰镇枣汁 + 凉皮" },
            tea:       "宜配:赞皇大枣红茶,煮到枣肉绵软,暖胃暖心",
            verse:     "「明月松间照,清泉石上流」 — 王维写水之境,藤龙瀑下亦得"
        },
        route: "景区入口 → 第一潭 → 沿溪步道 → 九瀑顶 → 玻璃栈道 → 下山",
        access: "石家庄→赞皇→藤龙山,车程约2小时。",
        tips: "夏季水量丰沛景色最佳,飞拉达需另行购票约150元。",
        gear: ["防滑徒步鞋", "速干衣", "1.5L 饮水", "防晒", "毛巾(戏水)", "手套(飞拉达)"],
        emergency: { local: "赞皇文旅局 0311-84221234", rescue: "藤龙山景区 0311-84273888", general: "110 / 120" },
        gpxNote: "景区线路清晰。",
        soundscape: { name: "山涧溪流", search: "stream creek mountain bamboo" },
        coords: { lon: 114.27, lat: 37.55 },
        lastUpdated: "2026-05-13"
    },
    {
        id: 9,
        name: "佛光山",
        location: "井陉县",
        difficulty: "hard",
        difficultyLabel: "困难",
        duration: "full",
        durationLabel: "一日",
        distance: "14 km",
        elevation: "约 1000 m",
        bestSeason: "秋季",
        seasonTags: ["autumn"],
        theme: { sky: ["#f0c89a", "#c89a6e"], far: "#8a8050", mid: "#5a6038", near: "#2d4a1f", accent: "ridge", sun: "sunset", primary: "#5a6038", soft: "#e8e0d0" },
        ratings: { stamina: 4, technical: 4, exposure: 5, retreat: 1, signal: 1 },
        techGrade: "T4",
        epithet: "佛光独行",
        poem: {
            title: "登幽州台歌",
            author: "陈子昂",
            dynasty: "唐",
            lines: ["前不见古人", "后不见来者", "念天地之悠悠", "独怆然而涕下"],
            note: "佛光山脊孤立无援,独行者方知天地之大,人之小,正合此千古绝唱。"
        },
        description: "未完全商业开发的徒步胜地,以原始山野景观吸引硬核驴友,需具备徒步经验。",
        features: [
            "未商业化的'野山',无门票无人挤",
            "山脊线徒步,视野开阔,适合穿越爱好者",
            "可顺穿天长古镇(秦皇古驿道遗迹)",
            "秋季层林尽染,但无人为修饰,纯原野美",
            "需自备饮水、补给与导航装备"
        ],
        waypoints: [
            { time: "07:00", name: "天长古镇集合", elev: "300m", scene: "🏘️", vista: "千年古镇石板路+古城墙,炊烟初起", note: "古道起点,补给最后机会" },
            { time: "08:00", name: "秦皇古道入口", elev: "400m", scene: "🛤️", vista: "秦代车辙印迹清晰可见,深陷石板", note: "石板车辙印迹清晰" },
            { time: "10:00", name: "山脊线起点", elev: "800m", scene: "⛰️", vista: "开阔山脊,视野极佳风过长草", note: "开始硬核徒步" },
            { time: "12:00", name: "佛光绝壁", elev: "1150m", scene: "🪨", vista: "崖顶午餐,脚下深谷云雾翻涌", note: "崖顶午餐,绝景" },
            { time: "14:30", name: "佛光顶", elev: "1290m", scene: "🌅", vista: "海拔1290米登顶,百里山色一览", note: "登顶,可见百里山色" },
            { time: "16:30", name: "西沟村", elev: "550m", scene: "🏡", vista: "山脚石头村落,炊烟袅袅升起", note: "村内有简易餐饮" },
            { time: "18:00", name: "包车返程", elev: "300m", scene: "🚐", vista: "村口包车点,夕阳挥别山野", note: "需提前联系当地车" }
        ],
        hiddenSpots: [
            "山脊中段有一片'红叶谷',9月底10月初无人涉足,色彩堪比黄山",
            "佛光顶北侧崖壁有摩崖石刻(年代不详),需绳降才能近距离观察",
            "西沟村李家老宅可吃到正宗'石磨豆腐宴',需提前一天电话预约"
        ],
        photography: "佛光顶日落+逆光人像极出片,但需要长焦镜头压缩远山。",
        food: "天长古镇缸炉烧饼、井陉煎饼、西沟石磨豆腐宴。",
        cuisine: {
            tagline: "野山归来,千年古道的一席素斋",
            signature: { name: "西沟石磨豆腐宴", icon: "🥢", price: "¥80-150", desc: "山间石磨现磨豆腐,做出豆腐脑、煎豆腐、酿豆腐、豆腐丸子十二样,清淡中见功夫,需提前一天电话预约" },
            snack:     { name: "缸炉烧饼夹咸菜", icon: "🥯", price: "¥5", desc: "硬核驴友的标配:轻、抗饿、不怕压。下山进村第一口,带着烟火气" },
            drink:     { name: "山泉煮土鸡蛋汤", icon: "🥚", price: "¥12", desc: "西沟山泉煮自家土鸡蛋,撒葱花淋香油,五分钟一锅,质朴到极致" },
            shop:      "推荐:西沟村·李家老宅(必须预约) / 天长古镇·秦皇古道食肆",
            seasonal:  { autumn: "秋宜:豆腐宴 + 山楂泡酒(秋采)", winter: "冬宜:全套豆腐锅 + 烤红薯" },
            tea:       "宜配:山间野生菊花茶,独行之后清心宁神",
            verse:     "「独坐幽篁里,弹琴复长啸」 — 王维独处之乐,豆腐宴可佐"
        },
        route: "井陉天长古镇 → 古道 → 山脊线 → 佛光顶 → 西沟村下撤",
        access: "需自驾至井陉,有路段路况较差。",
        tips: "户外经验不足者请勿单独前往,需准备充足饮水、干粮、地图与定位设备。",
        gear: ["高帮登山鞋", "登山杖", "3L 饮水", "充足干粮", "冲锋衣", "头灯", "急救包", "对讲机/卫星通讯", "GPS/离线地图", "保险/身份证"],
        emergency: { local: "井陉文旅局 0311-82021290", rescue: "井陉应急 0311-82038888", general: "110 / 120 / 蓝天救援 0311-87085222" },
        gpxNote: "强制要求下载GPX离线轨迹+离线地图,部分路段无信号。",
        soundscape: { name: "山脊孤风", search: "mountain ridge wind solitude" },
        coords: { lon: 114.13, lat: 38.04 },
        lastUpdated: "2026-05-09"
    },

    /* ===========================================================
       五岳 · 远望志(type: remote)
       与古人同游的文化拜谒,chronicle 字段记录历代登临
       =========================================================== */
    {
        id: 10,
        name: "东岳泰山",
        region: "wuyue",
        type: "remote",
        location: "山东 · 泰安",
        difficulty: "medium", difficultyLabel: "中等",
        duration: "full", durationLabel: "一日",
        distance: "约 9 km(红门—南天门—玉皇顶)",
        elevation: "海拔 1545 m",
        bestSeason: "春秋(避盛夏暴雨)",
        seasonTags: ["spring", "autumn"],
        theme: { sky: ["#f5d8a8", "#d4a878"], far: "#7a6850", mid: "#5a4838", near: "#2a2018", accent: "ridge", sun: "sunrise", primary: "#7a4f2c", soft: "#f0e0c8" },
        ratings: { stamina: 3, technical: 1, exposure: 2, retreat: 5, signal: 5 },
        techGrade: "T1",
        epithet: "五岳独尊",
        poem: {
            title: "望岳",
            author: "杜甫",
            dynasty: "唐 · 开元二十四年(736)",
            lines: ["岱宗夫如何", "齐鲁青未了", "造化钟神秀", "阴阳割昏晓", "荡胸生曾云", "决眦入归鸟", "会当凌绝顶", "一览众山小"],
            note: "杜甫二十四岁游齐赵望岳而作。'会当凌绝顶'一句千载之下犹烈,中国少年精神之绝唱。"
        },
        description: "五岳之首,中华民族精神图腾。自秦汉以来七十二代帝王封禅于此,无数文人写过它。它不只是山,是中国人心里那座必须登的山。",
        features: [
            "中国第一座入选世界双遗产的名山(1987)",
            "七十二帝王封禅地 · 自秦皇汉武至宋真宗",
            "孔子'登泰山而小天下' · 杜甫'会当凌绝顶'",
            "石刻博物馆:历代摩崖石刻 1800 余处",
            "看日出有'十回九不见'之说,反更动人"
        ],
        chronicle: [
            { year: "约前 500", dynasty: "春秋", person: "孔子",   event: "登泰山",                   legacy: "「登东山而小鲁,登泰山而小天下」 · 君子格局之始" },
            { year: "前 219",   dynasty: "秦",   person: "秦始皇", event: "首次封禅泰山",              legacy: "立无字碑 · 焚书前最后一道光" },
            { year: "前 110",   dynasty: "汉",   person: "汉武帝", event: "登泰山八次封禅",            legacy: "高呼万岁三声,山亦三应,'万岁山'之名始此" },
            { year: "736",      dynasty: "唐",   person: "杜甫",   event: "二十四岁游齐赵望岳",        legacy: "《望岳》「会当凌绝顶,一览众山小」" },
            { year: "742",      dynasty: "唐",   person: "李白",   event: "登泰山六首",                legacy: "「天门一长啸,万里清风来」 · 道家飞升之姿" },
            { year: "1009",     dynasty: "宋",   person: "宋真宗", event: "封禅泰山",                  legacy: "最后一位封禅的帝王,此后再无人配登" },
            { year: "1684",     dynasty: "清",   person: "康熙",   event: "御驾登山",                  legacy: "题「云峰」二字立于碑亭" },
            { year: "1748",     dynasty: "清",   person: "乾隆",   event: "十次登泰山",                legacy: "题字一百三十余处 · 文人皇帝的执念" }
        ],
        waypoints: [
            { time: "05:00", name: "红门宫起步", elev: "230m", scene: "🌌", vista: "天未明,松柏含露,香客与登山者同行", note: "传统登山起点" },
            { time: "06:30", name: "斗母宫·经石峪", elev: "400m", scene: "📜", vista: "北齐《金刚经》摩崖,字大如斗", note: "中华大字鼻祖" },
            { time: "08:00", name: "中天门", elev: "847m", scene: "🛕", vista: "上下分界,可乘缆车亦可徒步", note: "可选缆车节力" },
            { time: "10:00", name: "十八盘·南天门", elev: "1460m", scene: "🪜", vista: "石阶 1600 余级直插云霄,陡如登天", note: "泰山精魂所在" },
            { time: "11:00", name: "天街", elev: "1480m", scene: "🏯", vista: "云中市集,客栈酒幡随风", note: "可午餐补给" },
            { time: "12:00", name: "玉皇顶", elev: "1545m", scene: "🌄", vista: "极顶刻'五岳独尊',望齐鲁苍茫", note: "登顶 · 默念望岳一遍" }
        ],
        hiddenSpots: [
            "经石峪《金刚经》摩崖,清晨无人时最有禅意",
            "南天门夜宿(住天街客栈)看星空+日出,记得带羽绒服",
            "孔子登临处·望吴圣迹,大多数游客错过的孔子专属角落"
        ],
        photography: "南天门下十八盘逆光剪影最具张力;玉皇顶日出抢机位,4:30 就要占位。",
        food: "泰山豆腐宴、赤鳞鱼、煎饼卷大葱、女儿茶。",
        cuisine: {
            tagline: "封禅之山,饮食极简,与岱宗素朴相应",
            signature: { name: "泰山豆腐宴", icon: "🥢", price: "¥80-180", desc: "源自秦汉宫廷,泰山水做豆腐细如脂、白如玉。乾隆赞:'吃豆腐脑,润玉皇顶'" },
            snack:     { name: "煎饼卷大葱", icon: "🌯", price: "¥10", desc: "山东登山者的'压缩饼干',粗粮、抗饿、轻便。一卷在手,登顶不愁" },
            drink:     { name: "泰山女儿茶", icon: "🍵", price: "¥30/壶", desc: "泰山高山黄精嫩芽,清苦回甘,似饮山色一杯" },
            shop:      "推荐:天街·神憩宾馆素斋 / 红门路·泰安老豆腐",
            seasonal:  { spring: "春宜:山菇豆腐汤 + 香椿煎饼", autumn: "秋宜:泰山栗子粥 + 赤鳞鱼汤" },
            tea:       "宜配:女儿茶清饮,登顶后一杯,胸中再生一回风云",
            verse:     "「岱宗夫如何,齐鲁青未了」 — 望岳之初,先有一茶"
        },
        route: "红门 → 中天门 → 南天门 → 玉皇顶",
        access: "石家庄至泰安高铁约 2 小时,泰山站打车至红门 15 分钟。",
        tips: "盛夏多雷雨勿夜登;冬季有冰阶需冰爪。门票淡 100 / 旺 115。",
        gear: ["登山鞋", "充足饮水", "头灯(若夜登)", "羽绒服(山顶低温)", "雨衣"],
        emergency: { local: "泰山景区 0538-9669388", rescue: "泰山救援 0538-8066114", general: "110 / 120" },
        gpxNote: "全程石阶有标识,但岔路繁多,建议下载两步路'泰山经典线'。",
        soundscape: { name: "封禅古风·松涛", search: "taishan ancient wind pine" },
        coords: { lon: 117.13, lat: 36.25 },
        lastUpdated: "2026-05-23"
    },

    {
        id: 11,
        name: "西岳华山",
        region: "wuyue",
        type: "remote",
        location: "陕西 · 渭南",
        difficulty: "hard", difficultyLabel: "困难",
        duration: "full", durationLabel: "一日",
        distance: "约 12 km(玉泉院—北峰—南峰)",
        elevation: "海拔 2160 m",
        bestSeason: "春秋",
        seasonTags: ["spring", "autumn"],
        theme: { sky: ["#dceaf0", "#a8c8d8"], far: "#7080a0", mid: "#4a5878", near: "#1a2030", accent: "ridge", sun: "noon", primary: "#3e4a6e", soft: "#e0e8f0" },
        ratings: { stamina: 5, technical: 4, exposure: 5, retreat: 2, signal: 4 },
        techGrade: "T4",
        epithet: "奇险天下第一",
        poem: {
            title: "咏华山",
            author: "寇准(七岁作)",
            dynasty: "宋",
            lines: ["只有天在上", "更无山与齐", "举头红日近", "回首白云低"],
            note: "宋相寇准七岁登华山口占,'举头红日近'已见王相之器。中国童诗第一神品。"
        },
        description: "五岳最险,自古一条道,长空栈道、鹞子翻身闻名天下。道教全真派祖庭,陈抟、王重阳俱在此修真。",
        features: [
            "中国最险五岳,登顶有铁链可拽",
            "长空栈道:挂壁 30 cm 木板,下临千仞",
            "鹞子翻身:近垂直岩壁,需手脚并用",
            "金庸笔下'华山论剑'原型出处",
            "可夜爬看日出,'自古华山一条道'"
        ],
        chronicle: [
            { year: "约前 600", dynasty: "周",   person: "老子",     event: "西出函谷,传为登华山静修",       legacy: "「道法自然」 · 道教之源" },
            { year: "759",      dynasty: "唐",   person: "李白",     event: "登华山",                        legacy: "「西上太白峰,夕阳穷登攀」 · 仙人之姿" },
            { year: "约 900",   dynasty: "五代", person: "陈抟",     event: "隐居华山修道四十年",             legacy: "睡仙陈抟,留《无极图》《先天图》" },
            { year: "约 985",   dynasty: "宋",   person: "寇准",     event: "七岁随父登华山口占",             legacy: "《咏华山》 · 中国童诗神品" },
            { year: "1167",     dynasty: "金",   person: "王重阳",   event: "华山论道",                       legacy: "全真教初祖,武侠'华山论剑'原型" },
            { year: "约 803",   dynasty: "唐",   person: "韩愈",     event: "登华山苍龙岭",                   legacy: "脊薄如刀,韩愈痛哭遗书,后人传为笑谈" },
            { year: "1748",     dynasty: "清",   person: "袁枚",     event: "登华山记长空栈道",               legacy: "《随园诗话》记其'步步皆险,心胆俱裂'" }
        ],
        waypoints: [
            { time: "03:00", name: "玉泉院起步", elev: "400m", scene: "🌃", vista: "夜爬出发,头灯如星,'自古华山一条道'", note: "夜爬不烈日,推荐" },
            { time: "06:00", name: "北峰云台", elev: "1614m", scene: "🌄", vista: "日出第一观,云海漫顶,峰如孤台", note: "看日出最佳" },
            { time: "08:00", name: "苍龙岭", elev: "1850m", scene: "🐉", vista: "脊薄如刀,两侧深谷,韩愈痛哭处", note: "曾让韩愈写下绝命书" },
            { time: "10:00", name: "金锁关·东峰", elev: "2100m", scene: "🔒", vista: "万千锁挂石栏,情侣山盟", note: "可下鹞子翻身去下棋亭" },
            { time: "11:30", name: "南峰长空栈道", elev: "2160m", scene: "🪵", vista: "脚下千仞绝壁,身侧悬空栈板", note: "全程系扣,谨慎" },
            { time: "13:00", name: "西峰莲花", elev: "2080m", scene: "🌸", vista: "巨石如莲瓣,沉香救母传说处", note: "可缆车下山" }
        ],
        hiddenSpots: [
            "陈抟睡洞·北峰东侧,半小时无人徒步",
            "下棋亭·鹞子翻身后绝壁悬棋盘,赵匡胤输华山典故",
            "东峰看日出比北峰更孤绝,但需夜宿东峰宾馆"
        ],
        photography: "长空栈道挂壁人像、苍龙岭脊背剪影、西峰巨石压顶——华山是用广角镜的山。",
        food: "陕西凉皮、肉夹馍、华山酸辣粉、岩耳鸡汤。",
        cuisine: {
            tagline: "西岳之险,饮食以浓烈对应",
            signature: { name: "岩耳老母鸡", icon: "🍲", price: "¥120-180", desc: "华山崖壁上采的岩耳与散养老母鸡同炖,鲜如山雾化汤,补登山疲劳" },
            snack:     { name: "潼关肉夹馍", icon: "🥙", price: "¥10", desc: "腊汁肉酥而不腻,饼烤得起层。爬华山的标准燃料,一口顶半小时" },
            drink:     { name: "华阴老腔黄酒", icon: "🍶", price: "¥35", desc: "关中小米酿,温饮去寒。配老腔吼歌,陕西人的硬核" },
            shop:      "推荐:山顶·东峰宾馆 / 山下·华山玉泉院街",
            seasonal:  { winter: "冬宜:岩耳鸡汤 + 烫黄酒", autumn: "秋宜:陕西燃面 + 凉皮" },
            tea:       "宜配:商南泡花茶,登顶后清舌",
            verse:     "「只有天在上,更无山与齐」 — 寇准七岁,看天近"
        },
        route: "玉泉院 → 北峰 → 苍龙岭 → 金锁关 → 东/南/西峰",
        access: "石家庄至西安高铁约 6 小时,西安至华山高铁 30 分钟。",
        tips: "夜爬必备头灯/手套;冬季封山或局部封;西峰索道可救命。",
        gear: ["专业登山鞋", "手套(铁链磨手)", "头灯", "保暖", "充足饮水"],
        emergency: { local: "华山景区 0913-4362692", rescue: "华山救援 0913-4368799", general: "110 / 120" },
        gpxNote: "夜爬路线明确,但鹞子翻身/长空栈道需有人陪同。",
        soundscape: { name: "苍龙脊风", search: "huashan cliff wind" },
        coords: { lon: 110.08, lat: 34.49 },
        lastUpdated: "2026-05-23"
    },

    {
        id: 12,
        name: "南岳衡山",
        region: "wuyue",
        type: "remote",
        location: "湖南 · 衡阳",
        difficulty: "medium", difficultyLabel: "中等",
        duration: "full", durationLabel: "一日",
        distance: "约 11 km(南岳大庙—祝融峰)",
        elevation: "海拔 1300 m",
        bestSeason: "春秋",
        seasonTags: ["spring", "autumn"],
        theme: { sky: ["#e8d4d0", "#c8a8a0"], far: "#807060", mid: "#5a4040", near: "#2a1818", accent: "ridge", sun: "sunset", primary: "#8a4838", soft: "#f0d8d0" },
        ratings: { stamina: 3, technical: 2, exposure: 2, retreat: 4, signal: 4 },
        techGrade: "T2",
        epithet: "南岳独秀",
        poem: {
            title: "谒衡岳庙",
            author: "韩愈",
            dynasty: "唐 · 元和十四年(819)",
            lines: ["五岳祭秩皆三公", "四方环镇嵩当中", "火维地荒足妖怪", "天假神柄专其雄"],
            note: "韩愈贬潮州过衡岳,'潜心默祷若有应,岂非正直能感通'被誉为千古衡岳第一诗。"
        },
        description: "五岳唯一在江南,云雾终年,被称'文明奥区'。佛教南宗、道教福地、儒家书院汇聚一山,是中国宗教文化最丰厚的山。",
        features: [
            "南岳大庙 · 唯一一座祭五岳全制的庙",
            "祝融万丈拔地起 · 韩愈名句出处",
            "南台寺为日本曹洞宗祖庭",
            "石鼓书院 · 宋四大书院,周敦颐讲学",
            "祝融峰看日出,云海如棉絮万顷"
        ],
        chronicle: [
            { year: "约前 11 世纪", dynasty: "周",   person: "周天子",      event: "南巡望祭",                    legacy: "《尚书》「南岳」之名定" },
            { year: "约 711",       dynasty: "唐",   person: "怀让禅师",    event: "般若寺收马祖道一为徒",        legacy: "禅宗南岳一系,'磨砖作镜'公案" },
            { year: "768",          dynasty: "唐",   person: "杜甫",        event: "晚年漂泊登衡山",              legacy: "《望岳·南岳》「祝融万里南海风」" },
            { year: "819",          dynasty: "唐",   person: "韩愈",        event: "贬潮州过衡山",                legacy: "《谒衡岳庙》潜心默祷云开 · 千古名篇" },
            { year: "1167",         dynasty: "宋",   person: "朱熹/张栻",   event: "南岳同行讲学",                legacy: "理学'湖湘学派'核心,与岳麓书院齐名" },
            { year: "约 1265",      dynasty: "宋",   person: "文天祥",      event: "登祝融峰祭天",                legacy: "兵败前最后一次望江山,孤臣孽子心" },
            { year: "1644",         dynasty: "明清", person: "王船山",      event: "明亡后避居衡山",              legacy: "《船山遗书》三百卷 · 中国哲学的暗夜星" }
        ],
        waypoints: [
            { time: "06:00", name: "南岳大庙", elev: "100m", scene: "🛕", vista: "中国唯一祭五岳全制的大庙,香火不绝", note: "敬山先敬神" },
            { time: "07:30", name: "忠烈祠", elev: "300m", scene: "🕯️", vista: "祭抗战英烈,松柏森然", note: "近代史一站" },
            { time: "09:00", name: "南台寺·磨镜台", elev: "700m", scene: "🪞", vista: "日本曹洞宗祖庭,怀让磨砖处", note: "禅宗公案现场" },
            { time: "10:30", name: "半山亭", elev: "900m", scene: "🍵", vista: "云雾袅袅,可饮南岳云雾茶", note: "传统茶寮" },
            { time: "12:30", name: "祝融峰", elev: "1300m", scene: "🌅", vista: "登顶,'祝融万丈拔地起'韩愈处", note: "南岳之巅" }
        ],
        hiddenSpots: [
            "藏经殿后山·小路一条到磨镜台,人少景幽",
            "石鼓书院在衡阳市内,可顺路一访周敦颐讲学处",
            "祝融峰夜观星空,湖南光污染少,银河清晰"
        ],
        photography: "祝融峰云海日出,需在峰顶寺住一夜。",
        food: "湖南腊味、南岳素斋(全国闻名)、衡阳鱼粉。",
        cuisine: {
            tagline: "佛山禅厨,素斋一席胜过山珍",
            signature: { name: "南岳素全席", icon: "🥬", price: "¥80-200", desc: "祝圣寺、南台寺传承千年素斋,豆腐做出鱼形、香菇做出鸭味,色香味形俱足而无杀生" },
            snack:     { name: "衡阳鱼粉", icon: "🍜", price: "¥15", desc: "湘江野生鱼现熬汤,米粉滑过舌尖。下山进城第一碗" },
            drink:     { name: "南岳云雾茶", icon: "🍃", price: "¥40/壶", desc: "海拔 800m 雾中茶园,带板栗香、兰花韵" },
            shop:      "推荐:祝圣寺香积厨 / 半山亭茶寮 / 衡阳·彭记鱼粉",
            seasonal:  { spring: "春宜:春笋素烧 + 云雾新茶", summer: "夏宜:荷叶素粉 + 绿豆汤" },
            tea:       "宜配:云雾茶,茶中亦有'拈花一笑'意",
            verse:     "「祝融万丈拔地起,欲见不见轻烟里」 — 韩愈所见,亦你所见"
        },
        route: "南岳大庙 → 忠烈祠 → 南台寺 → 半山亭 → 祝融峰",
        access: "石家庄至衡山高铁约 8 小时,衡山西站打车至大庙 20 分钟。",
        tips: "湿润多雨备雨具;素斋需提前预订(尤其全席)。",
        gear: ["登山鞋", "雨衣", "登山杖", "充足饮水"],
        emergency: { local: "南岳景区 0734-5666188", rescue: "南岳救援 0734-5673199", general: "110 / 120" },
        gpxNote: "山路修整完好,标识清晰,可放心徒步。",
        soundscape: { name: "南岳松涛禅钟", search: "hengshan temple bell pine" },
        coords: { lon: 112.71, lat: 27.30 },
        lastUpdated: "2026-05-23"
    },

    {
        id: 13,
        name: "北岳恒山",
        region: "wuyue",
        type: "remote",
        location: "山西 · 大同浑源",
        difficulty: "medium", difficultyLabel: "中等",
        duration: "half", durationLabel: "半日",
        distance: "约 6 km(山门—天峰岭)",
        elevation: "海拔 2016 m",
        bestSeason: "春夏秋",
        seasonTags: ["spring", "summer", "autumn"],
        theme: { sky: ["#dac8a8", "#b09870"], far: "#7a7058", mid: "#5a5038", near: "#2a2418", accent: "ridge", sun: "noon", primary: "#6e5638", soft: "#ebe0c8" },
        ratings: { stamina: 3, technical: 2, exposure: 3, retreat: 5, signal: 4 },
        techGrade: "T2",
        epithet: "塞外神京 · 太行余脉",
        poem: {
            title: "登恒山",
            author: "贾岛",
            dynasty: "唐",
            lines: ["岩峦叠万重", "诡怪浩难测", "安能假羽翼", "聊一登绝顶"],
            note: "贾岛苦吟一生,登恒山见'岩峦叠万重',方知山势奇险胜过苦吟之难。"
        },
        description: "五岳中纬度最北,**与太行山系同根**。悬空寺挂崖一千五百年,'天下巨观'李白题字。塞外古战场,边塞诗之骨。",
        features: [
            "🌟 与太行同脉 — 北岳即太行山系最北一峰,你脚下的山,亦是它",
            "悬空寺 · 全世界唯一三教合一悬空寺",
            "李白题'壮观'二字,误多一点成'壮'",
            "明清以前北岳在河北曲阳,清顺治改恒山",
            "塞北边塞,杨家将传说处"
        ],
        chronicle: [
            { year: "前 110",   dynasty: "汉",   person: "汉武帝",   event: "封禅恒山(时在曲阳)",         legacy: "首次以国家名义祭北岳" },
            { year: "491",      dynasty: "北魏", person: "悬空寺始建", event: "三教合一悬空寺动工",         legacy: "挂崖千五百年不坠" },
            { year: "735",      dynasty: "唐",   person: "李白",     event: "登悬空寺",                    legacy: "题'壮观'二字,加一点显赞叹" },
            { year: "约 815",   dynasty: "唐",   person: "贾岛",     event: "登恒山",                      legacy: "《登恒山》「岩峦叠万重,诡怪浩难测」" },
            { year: "986",      dynasty: "宋",   person: "杨业",     event: "陈家谷恒山下战死",            legacy: "杨家将事迹原型,北宋抗辽之痛" },
            { year: "1654",     dynasty: "清",   person: "顺治帝",   event: "改祭山西恒山",                legacy: "北岳从此由曲阳移至浑源,千年定位重写" },
            { year: "1633",     dynasty: "明",   person: "徐霞客",   event: "登恒山记",                    legacy: "《徐霞客游记·游恒山日记》一卷" }
        ],
        waypoints: [
            { time: "07:00", name: "悬空寺", elev: "1500m", scene: "🛕", vista: "悬空寺挂壁,木栈架在虚无中", note: "李白题'壮观'处" },
            { time: "09:00", name: "停旨岭", elev: "1700m", scene: "📜", vista: "古碑'恒宗'二字,皇帝祭山驻跸", note: "下马敬山" },
            { time: "10:30", name: "朝殿·寝宫", elev: "1900m", scene: "🏯", vista: "北岳神祠,殿宇背山而立", note: "古祭祀核心" },
            { time: "11:30", name: "天峰岭顶", elev: "2016m", scene: "🌄", vista: "登顶,塞外苍茫,云冈相望", note: "北岳之巅" }
        ],
        hiddenSpots: [
            "悬空寺 6 点开门前到,无人独享",
            "恒山玄空寺侧脊小路,可远眺云冈石窟方向",
            "浑源县城内·永安寺壁画,辽金遗风,极少游客"
        ],
        photography: "悬空寺仰拍最具张力;天峰岭日落时回望塞外,可拍到层峦如海。",
        food: "山西刀削面、浑源凉粉、莜面栲栳栳、黄酒。",
        cuisine: {
            tagline: "塞北饮食,粗粝而真,与北岳同性",
            signature: { name: "莜面栲栳栳", icon: "🍙", price: "¥38", desc: "莜麦面卷成蜂窝状蒸熟,蘸羊肉臊子。山西人登北岳的硬核早餐" },
            snack:     { name: "浑源凉粉", icon: "🥗", price: "¥10", desc: "土豆淀粉做成,加恒山盐、本地辣油。下山进县城第一口" },
            drink:     { name: "北岳黄酒", icon: "🍶", price: "¥28", desc: "浑源县小米黄酒,温饮如棉,配莜面正合" },
            shop:      "推荐:浑源县城·李家凉粉 / 恒山脚下·北岳人家",
            seasonal:  { winter: "冬宜:羊汤莜面 + 烫黄酒", autumn: "秋宜:刀削面 + 浑源凉粉" },
            tea:       "宜配:山西边塞苦荞茶,粗粝而真",
            verse:     "「岩峦叠万重,诡怪浩难测」 — 贾岛见此,你亦见此"
        },
        route: "悬空寺 → 停旨岭 → 朝殿 → 天峰岭",
        access: "石家庄至大同高铁约 4 小时,大同至浑源汽车 1 小时。",
        tips: "塞北早晚温差大,夏季也需薄外套;悬空寺登道另收费。",
        gear: ["登山鞋", "薄外套", "雨衣", "充足饮水"],
        emergency: { local: "恒山景区 0352-8322142", rescue: "浑源应急 0352-8322110", general: "110 / 120" },
        gpxNote: "景区路径明确,无需 GPX,但建议提前看悬空寺开放时间。",
        soundscape: { name: "塞外古风", search: "frontier wind temple bell" },
        coords: { lon: 113.74, lat: 39.67 },
        lastUpdated: "2026-05-23"
    },

    {
        id: 14,
        name: "中岳嵩山",
        region: "wuyue",
        type: "remote",
        location: "河南 · 登封",
        difficulty: "medium", difficultyLabel: "中等",
        duration: "full", durationLabel: "一日",
        distance: "约 10 km(少林—二祖庵—连天峰)",
        elevation: "海拔 1492 m",
        bestSeason: "春秋",
        seasonTags: ["spring", "autumn"],
        theme: { sky: ["#e8d8b0", "#c8a878"], far: "#807058", mid: "#5a4838", near: "#2a2218", accent: "ridge", sun: "noon", primary: "#6a5028", soft: "#f0e0c0" },
        ratings: { stamina: 3, technical: 2, exposure: 2, retreat: 5, signal: 5 },
        techGrade: "T2",
        epithet: "天地之中",
        poem: {
            title: "送杨山人归嵩阳",
            author: "李白",
            dynasty: "唐",
            lines: ["归来桃花岩", "得憩云窗眠", "对岭人共语", "饮潭猿相连"],
            note: "李白送友归嵩,'对岭人共语,饮潭猿相连'——嵩山是隐士山,不在登,在归。"
        },
        description: "中岳居天地之中,儒释道三家在此交汇。少林寺、嵩阳书院、中岳庙各开一脉,是中华文化心脏。",
        features: [
            "**天地之中** · 历史建筑群入选世界遗产(2010)",
            "少林寺 · 禅宗祖庭、武术发源",
            "嵩阳书院 · 程颢程颐讲学,理学摇篮",
            "中岳庙 · 道教第六小洞天",
            "观星台 · 元代郭守敬测出回归年 365.2425 日"
        ],
        chronicle: [
            { year: "前 110",   dynasty: "汉",   person: "汉武帝", event: "登嵩山三呼万岁",                legacy: "「嵩高维岳,峻极于天」始为定" },
            { year: "527",      dynasty: "北魏", person: "达摩",   event: "少林寺面壁九年",                legacy: "禅宗东土初祖,'一苇渡江'传说" },
            { year: "约 700",   dynasty: "唐",   person: "武则天", event: "登嵩岳封禅",                    legacy: "唯一封中岳的帝王(避封泰山)" },
            { year: "约 770",   dynasty: "唐",   person: "李白",   event: "送友归嵩阳",                    legacy: "《送杨山人归嵩阳》「归来桃花岩」" },
            { year: "约 1070",  dynasty: "宋",   person: "程颢程颐", event: "嵩阳书院讲学",                legacy: "「程门立雪」典故出此,理学正脉" },
            { year: "1276",     dynasty: "元",   person: "郭守敬", event: "嵩山观星台测回归年",            legacy: "365.2425 日,比西方早三百年" },
            { year: "1639",     dynasty: "明",   person: "徐霞客", event: "登嵩山记",                      legacy: "《徐霞客游记·游嵩山日记》一卷" }
        ],
        waypoints: [
            { time: "07:00", name: "少林寺", elev: "350m", scene: "🛕", vista: "禅宗祖庭,塔林森立", note: "看僧人晨课" },
            { time: "09:00", name: "二祖庵", elev: "800m", scene: "🌿", vista: "慧可断臂处,清幽无人", note: "禅宗心法所在" },
            { time: "10:30", name: "三皇寨", elev: "1100m", scene: "🪜", vista: "栈道挂壁,'嵩山天险'", note: "嵩山看景最佳一线" },
            { time: "12:00", name: "连天峰", elev: "1492m", scene: "🌄", vista: "登顶,望嵩阳书院方向", note: "中岳之巅" },
            { time: "14:00", name: "嵩阳书院", elev: "400m", scene: "📖", vista: "三千年大将军柏,程颢程颐讲学处", note: "「程门立雪」典故现场" }
        ],
        hiddenSpots: [
            "塔林深处 · 历代少林高僧墓塔,清晨无人时如入古林",
            "观星台 · 在登封城内,郭守敬测年遗迹,大多数人略过",
            "二祖庵后山小径,通向少林寺另一侧出口,人迹罕至"
        ],
        photography: "塔林晨雾、嵩阳书院古柏、三皇寨栈道——嵩山影像层次最丰富。",
        food: "河南烩面、登封烧饼、少林素斋、洛阳水席。",
        cuisine: {
            tagline: "中州之味,儒释道三家口味同在一席",
            signature: { name: "少林素斋", icon: "🥬", price: "¥60-120", desc: "少林寺千年传承,'山中四宝'(松、香、竹、菌)入馔,清淡中见禅意" },
            snack:     { name: "登封烧饼", icon: "🥯", price: "¥3", desc: "面饼贴炉烤至焦黄,芝麻香满口,登山者最爱的'轻装行粮'" },
            drink:     { name: "嵩山黄盖酒", icon: "🍶", price: "¥30", desc: "登封小米酿造,微甜回酸,饮后通气活血" },
            shop:      "推荐:少林寺香积厨 / 登封市·烩面馆 / 嵩阳书院旁茶寮",
            seasonal:  { spring: "春宜:野菜烩面 + 嵩山新茶", autumn: "秋宜:菇笋素斋 + 烧饼" },
            tea:       "宜配:嵩山高山茶,饮后再读《传习录》一页",
            verse:     "「嵩高维岳,峻极于天」 — 《诗经》古韵,与你同在此山下"
        },
        route: "少林寺 → 二祖庵 → 三皇寨 → 连天峰 → 嵩阳书院",
        access: "石家庄至郑州高铁 2 小时,郑州至登封大巴 1.5 小时。",
        tips: "嵩山景区有多个入口,建议买联票(少林+三皇寨+嵩阳);夏季蚊虫多。",
        gear: ["登山鞋", "薄外套", "防蚊液", "充足饮水"],
        emergency: { local: "嵩山景区 0371-62749016", rescue: "登封应急 0371-62872110", general: "110 / 120" },
        gpxNote: "景区路径明确,但三皇寨—连天峰段建议下载离线轨迹。",
        soundscape: { name: "禅院钟鸣", search: "shaolin temple bell zen" },
        coords: { lon: 113.05, lat: 34.45 },
        lastUpdated: "2026-05-23"
    },
    {
        id: 15,
        name: "黄山",
        region: "hidden",
        type: "remote",
        location: "安徽 · 黄山市",
        difficulty: "hard", difficultyLabel: "困难",
        duration: "multi", durationLabel: "多日",
        distance: "约 15 km(慈光阁—玉屏—天都—北海—西海大峡谷)",
        elevation: "海拔 1864 m(莲花峰)",
        bestSeason: "秋季云海最佳,四季皆可",
        seasonTags: ["autumn", "spring"],
        theme: { sky: ["#d8e4ec", "#a0bccc"], far: "#6a8090", mid: "#3a4858", near: "#1a2230", accent: "cloud", sun: "noon", primary: "#3a4858", soft: "#e8eef2" },
        ratings: { stamina: 5, technical: 3, exposure: 4, retreat: 5, signal: 5 },
        techGrade: "T3",
        epithet: "黄岳归来",
        poem: {
            title: "送温处士归黄山白鹅峰旧居",
            author: "李白",
            dynasty: "唐",
            lines: ["黄山四千仞", "三十二莲峰", "丹崖夹石柱", "菡萏金芙蓉"],
            note: "李白笔下黄山:山如莲峰,崖如金芙蓉。徐霞客两登黄山,叹「五岳归来不看山,黄山归来不看岳」,自此天下名山为之逊色。"
        },
        description: "皖南奇山,松石云雪四绝。徐霞客两至,叹为天下第一。莲花、光明、天都三主峰并立,迎客松为山之眉目,云海为山之衣。",
        features: [
            "**五绝**:奇松、怪石、云海、温泉、冬雪",
            "迎客松 · 玉屏峰前,八百年虬枝向客,黄山地标",
            "莲花峰 · 主峰 1864 m,徐霞客「绝胜处」",
            "西海大峡谷 · 又名梦幻景区,栈道贴壁九转",
            "「五岳归来不看山,黄山归来不看岳」 — 徐霞客"
        ],
        chronicle: [
            { year: "747",     dynasty: "唐", person: "唐玄宗", event: "敕改黟山为黄山",       legacy: "「黄山」之名自此立(因传黄帝炼丹于此)" },
            { year: "约 750",  dynasty: "唐", person: "李白",   event: "游黄山赠温处士",       legacy: "「黄山四千仞,三十二莲峰」首咏黄山" },
            { year: "1233",    dynasty: "宋", person: "吴龙翰", event: "首登天都峰",           legacy: "有文字记录的天都峰第一人" },
            { year: "1616",    dynasty: "明", person: "徐霞客", event: "初登黄山",             legacy: "《游黄山日记》「踞石上,而仰瞻山色」" },
            { year: "1618",    dynasty: "明", person: "徐霞客", event: "再登黄山",             legacy: "「五岳归来不看山,黄山归来不看岳」名世" },
            { year: "1607",    dynasty: "明", person: "渐江",   event: "新安画派师黄山",       legacy: "黄山写生入画,「新安画派」自此立" },
            { year: "1985",    dynasty: "今", person: "联合国",   event: "黄山入世界双重遗产",   legacy: "自然与文化双遗产,东方山岳之冠" }
        ],
        waypoints: [
            { time: "Day1 08:00", name: "慈光阁",       elev: "900m",  scene: "⛩️", vista: "明万历古刹,登山起点", note: "可乘玉屏索道节力" },
            { time: "Day1 11:00", name: "迎客松 · 玉屏楼", elev: "1680m", scene: "🌲", vista: "八百年虬枝,正面华山如几案", note: "黄山地标,正面取景" },
            { time: "Day1 14:00", name: "莲花峰主峰",   elev: "1864m", scene: "🏔️", vista: "黄山之巅,三面绝壁,云海生于足下", note: "徐霞客「绝胜处」" },
            { time: "Day2 05:00", name: "光明顶观日",   elev: "1860m", scene: "🌅", vista: "黄山日出第一,云海如海潮金光中翻涌", note: "宿光明顶山庄方便看日出" },
            { time: "Day2 10:00", name: "西海大峡谷",   elev: "1500m", scene: "🪜", vista: "梦幻景区,栈道贴壁九转,云中行走", note: "环线下到云谷寺,缆车或徒步" }
        ],
        hiddenSpots: [
            "始信峰 · 在北海,峰名「至此方信黄山奇」,人少景奇",
            "排云亭后山 · 西海日落最佳,大多数人挤在丹霞峰",
            "汤口镇 · 山下温泉镇,有渐江画黄山的真迹拓片"
        ],
        photography: "迎客松正午顶光、光明顶日出云海、西海大峡谷晨雾,黄山经典三机位。",
        food: "徽菜:臭鳜鱼、毛豆腐、问政山笋、火腿炖甲鱼。山顶素食斋面。",
        cuisine: {
            tagline: "徽州古商之味,山珍水鲜皆有讲究",
            signature: { name: "臭鳜鱼", icon: "🐟", price: "¥80-120", desc: "腌渍发酵的鳜鱼,焖烧入味,闻臭吃香,徽菜代表" },
            snack:     { name: "黄山烧饼", icon: "🥯", price: "¥3-5",  desc: "梅干菜肉馅,炉壁烤焦,徽商出行之干粮" },
            drink:     { name: "祁门红茶", icon: "🍵", price: "¥30/壶", desc: "黄山脚下祁门所产,世界三大高香红茶之一,蜜糖香" },
            shop:      "推荐:汤口镇·老徽州 / 屯溪老街·徽府菜馆 / 山顶西海饭店",
            seasonal:  { autumn: "秋宜:石耳炖鸡 + 新摘秋茶", winter: "冬宜:雪里红炖肉 + 屯溪烫饭" },
            tea:       "宜配:黄山毛峰,黄山特产高山绿茶,味醇香远",
            verse:     "「五岳归来不看山,黄山归来不看岳」 — 徐霞客两至,叹为天下"
        },
        route: "慈光阁 → 玉屏楼(迎客松) → 莲花峰 → 光明顶 → 西海大峡谷 → 云谷寺",
        access: "石家庄至黄山北站高铁约 7 小时;山下汤口镇换乘景区大巴。",
        tips: "山顶冷,带保暖外套;雨衣必备(云雾即雨);周末提前订山顶山庄。",
        gear: ["登山鞋", "保暖外套(山顶夜<5℃)", "雨衣", "充电宝", "现金"],
        emergency: { local: "黄山景区 0559-5561111", rescue: "黄山救援 0559-5562290", general: "110 / 120" },
        gpxNote: "远望志 · 实地徒步循景区标线,无需 GPX。",
        soundscape: { name: "松涛云海", search: "huangshan wind pine cloud sea" },
        coords: { lon: 118.17, lat: 30.13 },
        lastUpdated: "2026-05-25"
    },
    {
        id: 16,
        name: "雁荡山",
        region: "hidden",
        type: "remote",
        location: "浙江 · 乐清",
        difficulty: "medium", difficultyLabel: "中等",
        duration: "full", durationLabel: "一日",
        distance: "约 8 km(灵峰—灵岩—大龙湫)",
        elevation: "海拔 1108 m(百冈尖)",
        bestSeason: "春秋,夜游灵峰别有意趣",
        seasonTags: ["spring", "autumn"],
        theme: { sky: ["#d4dae8", "#9aa4b8"], far: "#5a6478", mid: "#36404e", near: "#1a2028", accent: "ridge", sun: "noon", primary: "#36404e", soft: "#e4e8f0" },
        ratings: { stamina: 3, technical: 2, exposure: 3, retreat: 5, signal: 5 },
        techGrade: "T2",
        epithet: "天下奇秀",
        poem: {
            title: "梦溪笔谈 · 雁荡(节)",
            author: "沈括",
            dynasty: "宋",
            lines: ["温州雁荡山", "天下奇秀", "然自古图牒未尝有言者", "予观雁荡诸峰,皆峭拔险怪"],
            note: "沈括于《梦溪笔谈》首叙雁荡奇秀,并发流水侵蚀之地学之论,千年前已悟造山之理。"
        },
        description: "浙东海上名山,以「奇峰、灵岩、飞瀑、古洞、清泉」五绝著。沈括誉「天下奇秀」,谢灵运、徐霞客皆至。夜游灵峰,峰形似人禽,千变万化。",
        features: [
            "**天下奇秀** · 沈括《梦溪笔谈》定名",
            "灵峰夜景 · 双笋峰、犀牛望月、雄鹰敛翅,夜中峰形最幻",
            "大龙湫瀑布 · 落差 197 m,中国十大名瀑之一",
            "灵岩飞渡 · 表演艺人空中索行,惊心动魄",
            "沈括于此发流水侵蚀造山之论,中国地质学先声"
        ],
        chronicle: [
            { year: "约 423", dynasty: "南朝宋", person: "谢灵运", event: "游雁荡山下",         legacy: "「裹粮杖轻策」开山水诗中雁荡一脉" },
            { year: "631",   dynasty: "唐",    person: "诺距那",   event: "天台僧入雁荡修行", legacy: "雁荡山佛教自此立,「雁荡」之名渐显" },
            { year: "约 1075", dynasty: "宋",  person: "沈括",     event: "考察雁荡,作笔谈", legacy: "「天下奇秀」+ 流水侵蚀说,千年地学先声" },
            { year: "1613",  dynasty: "明",    person: "徐霞客",   event: "三登雁荡",         legacy: "《游雁宕山日记》三卷,《游记》开篇之作" },
            { year: "1614",  dynasty: "明",    person: "徐霞客",   event: "再登访雁湖",       legacy: "「雁宕之奇,不在山而在水」一论" }
        ],
        waypoints: [
            { time: "09:00", name: "灵峰",       elev: "200m",  scene: "🪨", vista: "合掌峰、双笋峰,奇形巨石环列", note: "白日观形,夜中观影" },
            { time: "10:30", name: "灵岩",       elev: "250m",  scene: "🏞️", vista: "天柱、展旗二峰对峙,飞渡表演处", note: "11:00 / 14:30 有飞渡表演" },
            { time: "13:00", name: "大龙湫",     elev: "300m",  scene: "💦", vista: "197 米飞瀑直下,雷声震谷", note: "雨季尤盛,枯水期变细" },
            { time: "15:30", name: "雁湖",       elev: "1046m", scene: "🏔️", vista: "山顶湖泊,秋雁宿此,故名雁荡", note: "山顶徐霞客「雁宕」名之所出" },
            { time: "19:30", name: "灵峰夜游",   elev: "200m",  scene: "🌙", vista: "月下峰影千变,犀牛望月、雄鹰敛翅", note: "雁荡精华,务必夜游" }
        ],
        hiddenSpots: [
            "净名谷 · 灵峰西侧,无人小谷,谢灵运题字处",
            "显胜门 · 雁荡北边,两峰夹一线天,门高百仞",
            "羊角洞 · 大龙湫上游,需越溪入,徐霞客「雁宕奇绝处」"
        ],
        photography: "灵峰夜景必拍(月光逆剪影)、大龙湫雨后正面、灵岩飞渡侧拍。",
        food: "温州海鲜+山珍:楠溪江田鱼、雁荡山笋、敲鱼面、姜茶。",
        cuisine: {
            tagline: "山海兼得,温州古味与雁荡山珍",
            signature: { name: "敲鱼面", icon: "🍜", price: "¥35-55", desc: "鱼肉敲打成面状,清汤滚煮,温州第一手艺" },
            snack:     { name: "雁荡山笋", icon: "🎋", price: "¥30/份", desc: "雨后毛竹笋,白灼或红烧,鲜甘脆嫩" },
            drink:     { name: "温州姜茶", icon: "🫖", price: "¥10",   desc: "红糖姜片煮成,雁山雨多湿气重,饮之祛寒" },
            shop:      "推荐:大荆镇·雁山农家 / 灵岩寺旁素斋 / 乐清市区·阿强敲鱼",
            seasonal:  { spring: "春宜:春笋炖咸肉 + 新茶", summer: "夏宜:楠溪江田鱼 + 绿豆汤" },
            tea:       "宜配:雁荡毛峰茶,生于火山岩石缝,味清冽",
            verse:     "「雁宕之奇,不在山而在水」 — 徐霞客一语中的"
        },
        route: "灵峰 → 灵岩(飞渡) → 大龙湫 → 雁湖(可选) → 夜返灵峰夜游",
        access: "石家庄至温州南站高铁约 9 小时;温州至雁荡景区大巴 1.5 小时。",
        tips: "夜游灵峰是雁荡精华;雨季瀑布最盛,但山路湿滑;雁湖往返需 4 小时。",
        gear: ["登山鞋", "雨衣", "手电(夜游)", "保暖薄外套"],
        emergency: { local: "雁荡景区 0577-62221116", rescue: "乐清救援 0577-61880110", general: "110 / 120" },
        gpxNote: "远望志 · 景区步道完备,无需 GPX。",
        soundscape: { name: "大龙湫飞瀑", search: "yandang waterfall echo" },
        coords: { lon: 121.05, lat: 28.40 },
        lastUpdated: "2026-05-25"
    },
    {
        id: 17,
        name: "武当山",
        region: "hidden",
        type: "remote",
        location: "湖北 · 十堰",
        difficulty: "medium", difficultyLabel: "中等",
        duration: "full", durationLabel: "一日",
        distance: "约 10 km(琼台—南岩—金顶)",
        elevation: "海拔 1612 m(天柱峰)",
        bestSeason: "春秋,避三伏与隆冬",
        seasonTags: ["spring", "autumn"],
        theme: { sky: ["#cfd8e8", "#8a9ab4"], far: "#5060700", mid: "#2a3848", near: "#101820", accent: "temple", sun: "warm", primary: "#2a3848", soft: "#e0e6f0" },
        ratings: { stamina: 3, technical: 2, exposure: 2, retreat: 5, signal: 5 },
        techGrade: "T2",
        epithet: "玄岳天下",
        poem: {
            title: "题武当山",
            author: "元好问",
            dynasty: "金",
            lines: ["天柱亭亭出翠微", "群峰朝拱势如归", "可怜八百神仙宅", "不见游人来扣扉"],
            note: "元遗山笔下武当:七十二峰朝大顶,二十四涧水流长。真武修道于此,明永乐大兴宫观,自此为玄岳之尊。"
        },
        description: "鄂西道宗祖庭,真武修道地。明永乐敕修,八宫二观三十六庵堂,被誉「亘古无双胜境,天下第一仙山」。太极拳由此演衍。",
        features: [
            "**玄岳之尊** · 明永乐敕封「治世玄岳」,在五岳之上",
            "金殿 · 天柱峰顶,全铜鎏金,五百年风雷不锈,殿内真武像",
            "南岩宫 · 飞檐悬于绝壁,「天下第一香炉」探出三米",
            "紫霄宫 · 武当最大宫观,主奉真武大帝",
            "太极发源 · 张三丰创太极拳于武当,内家拳宗祖"
        ],
        chronicle: [
            { year: "约 1300", dynasty: "宋元", person: "张三丰", event: "修道武当,创太极拳",       legacy: "内家拳宗祖,武当道脉至今承续" },
            { year: "1413",    dynasty: "明",   person: "明成祖", event: "敕修武当宫观三十三处",   legacy: "三十年大兴土木,今所见格局自此立" },
            { year: "1416",    dynasty: "明",   person: "明成祖", event: "封武当为「大岳太和山」", legacy: "号「治世玄岳」,五岳之外又一岳" },
            { year: "1552",    dynasty: "明",   person: "嘉靖帝", event: "重修金殿铸像",           legacy: "今日金顶之像,即此时所铸" },
            { year: "1610",    dynasty: "明",   person: "袁中道", event: "游武当",                 legacy: "公安派笔下「天柱七十二峰各有名」" },
            { year: "1994",    dynasty: "今",   person: "联合国",   event: "武当入世界文化遗产",     legacy: "古建群规模为中国道教第一" }
        ],
        waypoints: [
            { time: "07:30", name: "琼台中观",   elev: "600m",  scene: "⛩️", vista: "古观掩在松柏间,索道下站", note: "可乘金顶索道节力" },
            { time: "09:00", name: "南岩宫",     elev: "1100m", scene: "🛕", vista: "飞檐悬绝壁,「天下第一香炉」探出岩端", note: "武当最险也最美" },
            { time: "10:30", name: "朝天宫",     elev: "1300m", scene: "⛩️", vista: "登金顶分界,皇室上山在此换装", note: "「人间天上」之分" },
            { time: "12:00", name: "金殿 · 天柱峰", elev: "1612m", scene: "🏛️", vista: "全铜鎏金,五百年风雷不锈,殿内真武大帝像", note: "可上香,可绕殿" },
            { time: "15:00", name: "紫霄宫",     elev: "800m",  scene: "🏯", vista: "武当最大宫观,十方丛林", note: "下午光线最美" }
        ],
        hiddenSpots: [
            "太子坡 · 真武修道前为太子读书处,九曲黄河墙",
            "磨针井 · 「铁杵磨成针」典出此,真武回心处",
            "五龙宫 · 武当最古道场(唐建),今为废墟,清幽无人"
        ],
        photography: "金顶日出云海、南岩宫飞檐侧拍、紫霄宫黄昏古柏,武当三经典。",
        food: "武当道家素斋:四生盘、太和豆腐、五子献寿。十堰本地豆皮、热干面。",
        cuisine: {
            tagline: "道家素斋为正,荤腥不入山门",
            signature: { name: "武当道家素斋", icon: "🥬", price: "¥80-180", desc: "五子献寿、八卦豆腐、四生盘 — 千年道斋,清淡养性" },
            snack:     { name: "武当神仙叶凉粉", icon: "🌿", price: "¥8",  desc: "野生神仙叶揉汁凝粉,翠绿如玉,清热祛暑" },
            drink:     { name: "武当道茶", icon: "🍵", price: "¥30/壶", desc: "山高云雾所生,道家清修茶,味淡而远" },
            shop:      "推荐:紫霄宫斋堂 / 南岩宫斋堂 / 山下武当镇·三丰素馆",
            seasonal:  { autumn: "秋宜:山菌烩素 + 武当道茶", winter: "冬宜:温汤豆腐 + 黄精汤" },
            tea:       "宜配:武当黄精茶,真武修道首选食物,温补不燥",
            verse:     "「亘古无双胜境,天下第一仙山」 — 明成祖御笔"
        },
        route: "琼台 → 南岩宫 → 朝天宫 → 金顶(天柱峰) → 下山紫霄宫",
        access: "石家庄至武当山高铁站约 5 小时;山下乘景区大巴换索道至琼台。",
        tips: "金顶风极大,务必带防风衣;道宫多禁拍内殿,先问可否;不宜穿短裤入殿。",
        gear: ["登山鞋", "防风外套", "充电宝", "现金(山顶香烛)"],
        emergency: { local: "武当景区 0719-5689001", rescue: "丹江口救援 0719-5666120", general: "110 / 120" },
        gpxNote: "远望志 · 景区索道与步道齐备,无需 GPX。",
        soundscape: { name: "金顶钟磬", search: "wudang temple chime taoist" },
        coords: { lon: 111.00, lat: 32.40 },
        lastUpdated: "2026-05-25"
    },
    {
        id: 18,
        name: "峨眉山",
        region: "hidden",
        type: "remote",
        location: "四川 · 乐山",
        difficulty: "hard", difficultyLabel: "困难",
        duration: "multi", durationLabel: "多日",
        distance: "约 18 km(报国寺—清音阁—洪椿坪—金顶)",
        elevation: "海拔 3099 m(万佛顶)",
        bestSeason: "夏避暑、冬观雪,春秋亦佳",
        seasonTags: ["summer", "winter"],
        theme: { sky: ["#dde4e0", "#9eb0a8"], far: "#5a7068", mid: "#2c4038", near: "#101c18", accent: "cloud", sun: "warm", primary: "#2c4038", soft: "#e6ece8" },
        ratings: { stamina: 5, technical: 3, exposure: 3, retreat: 4, signal: 4 },
        techGrade: "T3",
        epithet: "佛光普贤",
        poem: {
            title: "登峨眉山",
            author: "李白",
            dynasty: "唐",
            lines: ["蜀国多仙山", "峨眉邈难匹", "周流试登览", "绝怪安可悉"],
            note: "李白生长蜀中,峨眉是少年游处。后赋《峨眉山月歌》「峨眉山月半轮秋,影入平羌江水流」,千古绝唱。"
        },
        description: "川蜀佛国,普贤菩萨道场,中国四大佛山之一。山高三千,从亚热带到亚寒带四时同山。金顶四绝:日出、云海、佛光、圣灯。",
        features: [
            "**佛门四大名山之一** · 普贤菩萨道场",
            "金顶 · 海拔 3079m,日出云海佛光圣灯四绝",
            "万佛顶 · 3099m 峨眉真正最高点,人少景奇",
            "清音阁、洪椿坪 · 半山禅意,黑龙江白龙江汇流",
            "「峨眉山月半轮秋」 — 李白少年游处"
        ],
        chronicle: [
            { year: "约 100", dynasty: "汉",   person: "蒲公",     event: "见普贤光相于峨眉",   legacy: "峨眉成普贤道场,佛教初入山" },
            { year: "约 750", dynasty: "唐",   person: "李白",     event: "游峨眉作《峨眉山月歌》", legacy: "「峨眉山月半轮秋」千古绝唱" },
            { year: "约 760", dynasty: "唐",   person: "杜甫",     event: "登峨眉访道",           legacy: "《峨眉山》「冬日蜀地暖,峨眉雪正寒」" },
            { year: "980",    dynasty: "宋",   person: "白水普贤", event: "造铜铸普贤像七米",     legacy: "「西天瑞像」,峨眉佛艺极盛" },
            { year: "1614",   dynasty: "明",   person: "徐霞客",   event: "登峨眉",               legacy: "《滇游日记》先途经此,叹「峨之高,何止于五岳」" },
            { year: "1996",   dynasty: "今",   person: "联合国",     event: "峨眉入世界双重遗产",   legacy: "与乐山大佛同列,文化与自然双遗" }
        ],
        waypoints: [
            { time: "Day1 08:00", name: "报国寺",       elev: "550m",  scene: "⛩️", vista: "峨眉佛事中心,千年古刹,起点", note: "可乘观光车节力" },
            { time: "Day1 11:00", name: "清音阁",       elev: "710m",  scene: "💧", vista: "黑白二龙江汇流,「清音双桥」", note: "半山禅意,午餐处" },
            { time: "Day1 14:30", name: "洪椿坪",       elev: "1120m", scene: "🌲", vista: "森林荫蔽古寺,洪椿千年", note: "可宿洪椿坪客舍" },
            { time: "Day2 04:30", name: "金顶 · 普贤像", elev: "3079m", scene: "🏛️", vista: "全铜普贤十方像,日出云海皆在脚下", note: "可索道直上,或从洪椿坪步行九小时" },
            { time: "Day2 09:00", name: "万佛顶",       elev: "3099m", scene: "🏔️", vista: "峨眉真正最高峰,云雾深处人迹少", note: "金顶西行一小时" }
        ],
        hiddenSpots: [
            "舍身崖 · 金顶西南,云海最盛处,亦古来观佛光地",
            "九老洞 · 千年道场,峨眉灵猴最早出没",
            "黑水寺 · 半山深处,鲜有游客,茶山幽静"
        ],
        photography: "金顶日出云海(春秋多)、佛光(午后阳光斜照云海)、万佛顶雪景。",
        food: "川菜+佛家素斋:钵钵鸡、雪魔芋烧鸭、峨眉素斋、张包子。",
        cuisine: {
            tagline: "蜀辣山素皆有,半山饮食两味分",
            signature: { name: "峨眉雪魔芋", icon: "🍲", price: "¥40-60", desc: "高山魔芋经冬雪冻制,Q 弹入味,峨眉素斋之冠" },
            snack:     { name: "张包子", icon: "🥟", price: "¥3",    desc: "峨眉市百年老店,皮薄馅丰,登山前必填" },
            drink:     { name: "竹叶青茶", icon: "🍵", price: "¥40/壶", desc: "峨眉山高山绿茶,色翠形如竹叶,味鲜冽" },
            shop:      "推荐:报国寺斋堂 / 山下峨眉市·张包子 / 金顶素斋",
            seasonal:  { summer: "夏宜:冰粉 + 雪魔芋凉拌", winter: "冬宜:钵钵鸡 + 烫白酒" },
            tea:       "宜配:峨眉竹叶青,茶圣陆羽叹「峨山多药草,茶尤良」",
            verse:     "「峨眉山月半轮秋,影入平羌江水流」 — 李太白"
        },
        route: "报国寺 → 清音阁 → 洪椿坪(宿) → 金顶 → 万佛顶",
        access: "石家庄至成都东高铁约 9 小时;成都至峨眉景区动车 1.5 小时。",
        tips: "金顶海拔三千,务必带羽绒;猴区不挑衅、不喂食、收好食物;雨季栈道湿滑。",
        gear: ["登山鞋", "羽绒服(金顶<0℃)", "防猴竹竿(景区有租)", "雨衣"],
        emergency: { local: "峨眉景区 0833-5525203", rescue: "峨眉应急 0833-5525555", general: "110 / 120" },
        gpxNote: "远望志 · 景区步道齐备,索道直达金顶。",
        soundscape: { name: "金顶梵呗", search: "emei buddhist chant temple" },
        coords: { lon: 103.48, lat: 29.55 },
        lastUpdated: "2026-05-25"
    },
    {
        id: 19,
        name: "终南山",
        region: "hidden",
        type: "remote",
        location: "陕西 · 西安",
        difficulty: "medium", difficultyLabel: "中等",
        duration: "full", durationLabel: "一日",
        distance: "约 10 km(翠华—南五台—太兴山或环山)",
        elevation: "海拔 2604 m(终南太白段最高)",
        bestSeason: "秋为正,春次之",
        seasonTags: ["autumn", "spring"],
        theme: { sky: ["#d8d8c8", "#a0a088"], far: "#605838", mid: "#2e2818", near: "#0c0a06", accent: "cloud", sun: "warm", primary: "#2e2818", soft: "#ece8d8" },
        ratings: { stamina: 3, technical: 2, exposure: 2, retreat: 5, signal: 3 },
        techGrade: "T2",
        epithet: "终南云隐",
        poem: {
            title: "终南别业",
            author: "王维",
            dynasty: "唐",
            lines: ["中岁颇好道", "晚家南山陲", "行到水穷处", "坐看云起时"],
            note: "王维晚年居终南辋川,作《终南别业》,「行到水穷处,坐看云起时」十字尽其禅意。此句亦为行山志开卷之诗,今卷十归山,正合归来之意。"
        },
        description: "关中之南,长安背山。自古隐者之乡,陶弘景、王维、孙思邈、终南五祖皆居之。今仍有数千隐士入山修行,「终南捷径」一词亦出于此。",
        features: [
            "**隐者之山** · 自魏晋至今,千载隐居传统不绝",
            "终南五祖 · 全真道五祖修真处(王重阳、丘处机等)",
            "王维辋川别业 · 「空山新雨后,天气晚来秋」即此处",
            "南五台 · 观音、文殊、清凉、舍身、灵应五台,佛家圣地",
            "孙思邈隐居药王山,《千金方》成于此"
        ],
        chronicle: [
            { year: "约 350", dynasty: "东晋", person: "王嘉",   event: "隐居终南楼观",         legacy: "《拾遗记》成于此,「终南隐」典出" },
            { year: "约 500", dynasty: "南齐", person: "陶弘景", event: "山中宰相,不入朝",     legacy: "「山中宰相」之号自此立" },
            { year: "约 640", dynasty: "唐",   person: "孙思邈", event: "终南药王山著《千金方》", legacy: "中国医学万古经典,药王之号" },
            { year: "约 760", dynasty: "唐",   person: "王维",   event: "辋川别业",             legacy: "「行到水穷处,坐看云起时」千古名句" },
            { year: "约 1170", dynasty: "金",  person: "王重阳", event: "重阳宫修真",           legacy: "全真道祖庭,丘处机、马钰等七真子由此衍" },
            { year: "约 705", dynasty: "唐",   person: "卢藏用", event: "走「终南捷径」入仕",   legacy: "「终南捷径」典出,讥假隐求名者" }
        ],
        waypoints: [
            { time: "08:00", name: "翠华山",     elev: "1200m", scene: "🏞️", vista: "天池古湫,唐玄宗避难处", note: "可半日轻游" },
            { time: "10:00", name: "南五台",     elev: "1688m", scene: "🛕", vista: "五峰并列,观音庙居顶", note: "佛家五台,登山主线" },
            { time: "12:00", name: "西竹林",     elev: "1500m", scene: "🌿", vista: "千年竹林,王维「独坐幽篁里」处", note: "辋川风物今犹在" },
            { time: "14:00", name: "重阳宫",     elev: "800m",  scene: "⛩️", vista: "全真道祖庭,王重阳修真处", note: "山下平地,可顺路" },
            { time: "16:00", name: "净业寺",     elev: "1100m", scene: "🌲", vista: "南山律宗祖庭,鲜有游人", note: "鉴真东渡前讲律于此" }
        ],
        hiddenSpots: [
            "嘉午台 · 终南正脊,人迹罕至,徒步爱好者首选",
            "辋川 · 王维旧居遗址,蓝田县境内,今见碑无楼",
            "石砭峪 · 山中隐士聚居处,问路可见茅棚"
        ],
        photography: "南五台晨雾、翠华山天池倒影、终南脊线晚霞。",
        food: "陕菜+终南山野味:葫芦头、岐山臊子面、终南山野菌、菜疙瘩。",
        cuisine: {
            tagline: "关中老味,终南山下三千年长安食制",
            signature: { name: "葫芦头泡馍", icon: "🍲", price: "¥30-50", desc: "猪大肠去腥精炖,馍块掰入,汤清味厚,长安老味" },
            snack:     { name: "终南菜疙瘩", icon: "🥬", price: "¥15",   desc: "山间野菜揉面团,蒸熟蘸蒜醋,隐士日常之食" },
            drink:     { name: "终南山泉水", icon: "💧", price: "免费",   desc: "翠华山下凉泉,清甘冽冽,王维笔下「清泉石上流」" },
            shop:      "推荐:西安·春发生葫芦头(百年老店) / 翠华山下·农家素面 / 重阳宫旁茶寮",
            seasonal:  { autumn: "秋宜:野菌烩面 + 新核桃", winter: "冬宜:羊肉泡馍 + 黄酒一壶" },
            tea:       "宜配:陕青(终南秦巴茶),陶弘景隐山时常饮",
            verse:     "「行到水穷处,坐看云起时」 — 王摩诘,亦行山志开卷之诗"
        },
        route: "翠华山 → 南五台 → 西竹林 → 重阳宫(山下) → 净业寺",
        access: "石家庄至西安北高铁约 5 小时;西安市区至终南各景区车程 1-2 小时。",
        tips: "终南支脉极广,一日难尽,选一两处即可;山中隐士勿打扰、勿拍照;秋季气温变化大。",
        gear: ["登山鞋", "薄外套", "充足饮水", "现金"],
        emergency: { local: "西安长安区文旅 029-85291888", rescue: "终南山救援 029-85688110", general: "110 / 120" },
        gpxNote: "远望志 · 终南支脉甚多,深入需向导。",
        soundscape: { name: "终南云水", search: "zhongnan mountain wind temple" },
        coords: { lon: 108.95, lat: 33.90 },
        lastUpdated: "2026-05-25"
    }
];
